<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.tianji</groupId><artifactId>tj-compact</artifactId><version>1.0.0</version></parent><artifactId>tj-identity-app</artifactId><dependencies><dependency><groupId>com.tianji</groupId><artifactId>tj-compact-runtime</artifactId><version>1.0.0</version></dependency><dependency><groupId>com.tianji</groupId><artifactId>tj-auth-service</artifactId><version>1.0.0</version></dependency><dependency><groupId>com.tianji</groupId><artifactId>tj-user</artifactId><version>1.0.0</version></dependency></dependencies><build><finalName>tj-identity-app</finalName><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId><configuration><skip>false</skip><mainClass>com.tianji.compact.IdentityApplication</mainClass></configuration></plugin></plugins></build></project>