<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.tianji</groupId><artifactId>tjxt</artifactId><version>1.0.0</version></parent><artifactId>tj-compact</artifactId><packaging>pom</packaging><modules><module>runtime</module><module>identity</module><module>commerce</module><module>education</module><module>support</module></modules></project>