<script setup lang="ts">
import zhCn from 'element-plus/es/locale/lang/zh-cn';import EnvironmentBanner from '../../../packages/shared/src/EnvironmentBanner.vue';
import {ref,onMounted,computed} from 'vue';import {useRoute} from 'vue-router';import {useSession} from '../../../packages/shared/src/session';import {useOperations} from '../../../packages/shared/src/operations';import {useTask} from '../../../packages/shared/src/ui';import Status from '../../../packages/shared/src/Status.vue';import {resources} from './resources';
const route=useRoute(),session=useSession(),ops=useOperations(),task=useTask(),username=ref(''),password=ref('');onMounted(()=>{if(session.token)void ops.resume();});
const groups=[{name:'教学内容',keys:['courses','media','questions']},{name:'用户与权限',keys:['students','staff','roles','privileges']},{name:'营销与交易',keys:['coupons','orders','refunds']},{name:'通知管理',keys:['templates','notices']}];
const pageTitle=computed(()=>resources[route.path.split('/')[1]||'']?.title||({'/':'数据看板','/exams':'试卷与评分','/reliability':'失败与补偿任务','/operations':'操作记录','/role-permissions':'角色权限绑定','/audit':'管理操作审计'}[route.path]||'管理工作台'));
</script>
<template><el-config-provider :locale="zhCn"><div v-if="!session.token || !session.admin" class="admin-login"><div class="card login"><img class="login-brand" src="/brand-logo.png" alt="天机学堂"/><h1>天机学堂管理中心</h1><p class="muted">让教学与管理，更有条理</p><Status :busy="task.busy.value" :error="task.error.value || session.expiredMessage"/><el-form label-position="top" @submit.prevent="task.run(()=>session.login(username,password,true))"><el-form-item label="账号"><el-input v-model="username" autocomplete="username" aria-label="账号" size="large"/></el-form-item><el-form-item label="密码"><el-input v-model="password" type="password" autocomplete="current-password" aria-label="密码" show-password size="large"/></el-form-item><el-button type="primary" native-type="submit" size="large" class="login-submit" :disabled="task.busy.value || !username || !password">登录管理端</el-button></el-form></div></div>
<div v-else class="layout admin-shell"><aside class="sidebar admin-sidebar"><RouterLink to="/" class="admin-brand"><img src="/brand-logo.png" alt="天机学堂"/><span>教学管理平台</span></RouterLink><nav><RouterLink v-if="session.role!==3" to="/" exact-active-class="selected">▦　数据看板</RouterLink><template v-if="session.role!==3"><section v-for="group in groups" :key="group.name" class="nav-group"><small>{{group.name}}</small><RouterLink v-for="key in group.keys" :key="key" :to="'/'+key" exact-active-class="selected">{{resources[key]!.title}}</RouterLink></section><RouterLink to="/role-permissions" exact-active-class="selected">角色权限绑定</RouterLink></template><section class="nav-group"><small>教学与系统运维</small><RouterLink to="/exams" exact-active-class="selected">试卷与评分</RouterLink><RouterLink v-if="session.role!==3" to="/reliability" exact-active-class="selected">失败与补偿任务</RouterLink><RouterLink v-if="session.role!==3" to="/audit" exact-active-class="selected">管理操作审计</RouterLink><RouterLink to="/operations" exact-active-class="selected">操作记录</RouterLink></section></nav></aside>
<main class="main admin-main"><header class="topbar"><div><small class="muted">天机学堂 / 管理工作台</small><p class="workspace-title">{{pageTitle}}</p></div><div class="header-actions"><span class="admin-role">{{session.role===3?'教师工作台':'管理工作台'}}</span><el-button text @click="task.run(()=>session.logout())">退出登录</el-button></div></header><Status :error="task.error.value || session.expiredMessage"/><EnvironmentBanner/><RouterView/></main></div></el-config-provider></template>
