import type {Row} from '../../../packages/shared/src/ui';
export interface Field{key:string;label:string;kind?:'number'|'boolean'|'text'|'long'|'ids'|'options'|'datetime';required?:boolean;initial?:unknown}
export interface Action{label:string;path:(row:Row)=>string;method:string;body?:(row:Row)=>unknown}
export interface Resource{title:string;list:string;columns:[string,string][];fields?:Field[];create?:string;update?:(row:Row)=>string;detail?:(row:Row)=>string;remove?:(row:Row)=>string;actions?:Action[]}
const f=(key:string,label:string,kind:Field['kind']='text',initial?:unknown):Field=>({key,label,kind,initial});
export const resources:Record<string,Resource>={
 courses:{title:'课程管理',list:'/admin/course/courses/page',columns:[['id','课程 ID'],['name','课程名称'],['price','价格（分）'],['status','状态']],create:'/admin/course/courses/baseInfo/save',update:()=>'/admin/course/courses/baseInfo/save',detail:r=>'/admin/course/courses/baseInfo/'+r.id+'?see=false',fields:[f('name','课程名称'),f('thirdCateId','三级分类 ID'),f('coverUrl','封面地址'),f('free','免费课程','boolean',false),f('price','价格（分）','number',0),f('purchaseEndTime','购买截止','datetime'),f('validDuration','学习有效期（月，0 永久）','number',0),f('introduce','课程介绍','long'),f('usePeople','适用人群'),f('detail','课程详情','long')],remove:r=>'/admin/course/courses/delete/'+r.id,actions:[{label:'上架',path:()=>'/admin/course/courses/upShelf',method:'POST',body:r=>({id:r.id})},{label:'下架',path:()=>'/admin/course/courses/downShelf',method:'POST',body:r=>({id:r.id})}]},
 media:{title:'媒资管理',list:'/admin/media/medias',columns:[['id','媒资 ID'],['filename','文件名'],['duration','时长'],['useTimes','引用次数'],['creater','创建人']],remove:r=>'/admin/media/medias/'+r.id},
 questions:{title:'题库',list:'/admin/exam/questions/page',columns:[['id','题目 ID'],['name','题干'],['type','类型'],['score','分值'],['difficulty','难度']],create:'/admin/exam/questions',update:r=>'/admin/exam/questions/'+r.id,detail:r=>'/admin/exam/questions/'+r.id,remove:r=>'/admin/exam/questions/'+r.id,fields:[f('name','题干','long'),f('type','类型 1 单选 / 2 多选 / 3 不定项 / 4 判断 / 5 主观','number',1),f('difficulty','难度 1 简单 / 2 中等 / 3 困难','number',1),f('score','分值','number',10),f('cateIds','分类 ID，逗号分隔','ids'),f('options','每行一个选项','options'),f('answer','标准答案'),f('analysis','答案解析','long')]},
 students:{title:'学生管理',list:'/admin/user/students/page',columns:[['id','用户 ID'],['name','姓名'],['cellPhone','手机'],['status','状态']],actions:[{label:'禁用',path:r=>'/admin/user/users/'+r.id+'/status/0',method:'PUT'},{label:'启用',path:r=>'/admin/user/users/'+r.id+'/status/1',method:'PUT'}]},
 staff:{title:'教师与员工',list:'/admin/user/staffs/page',columns:[['id','用户 ID'],['name','姓名'],['cellPhone','手机'],['roleName','角色']],create:'/admin/user/users',update:r=>'/admin/user/users/'+r.id,detail:r=>'/admin/user/users/'+r.id,fields:[f('name','姓名'),f('username','账号'),f('cellPhone','手机'),f('type','用户类型 3 教师 / 1 员工','number',3),f('roleId','角色 ID')],actions:[{label:'重置密码',path:r=>'/admin/user/users/'+r.id+'/password/default',method:'PUT'}]},
 roles:{title:'角色',list:'/admin/auth/roles/list',columns:[['id','角色 ID'],['name','角色名称'],['code','角色代码']],create:'/admin/auth/roles',update:r=>'/admin/auth/roles/'+r.id,remove:r=>'/admin/auth/roles/'+r.id,fields:[f('name','角色名称'),f('code','角色代码'),f('description','说明','long')]},
 privileges:{title:'接口权限',list:'/admin/auth/privileges',columns:[['id','权限 ID'],['intro','说明'],['method','请求方法'],['uri','接口路径']],create:'/admin/auth/privileges',update:r=>'/admin/auth/privileges/'+r.id,fields:[f('intro','权限说明'),f('menuId','所属菜单 ID'),f('method','请求方法','text','GET'),f('uri','接口路径'),f('internal','内部接口','boolean',false)]},
 coupons:{title:'优惠券营销',list:'/admin/promotion/coupons/page',columns:[['id','优惠券 ID'],['intro','说明'],['totalNum','总库存'],['issueNum','已发放'],['usedNum','已使用'],['status','状态']],create:'/admin/promotion/coupons',update:r=>'/admin/promotion/coupons/'+r.id,detail:r=>'/admin/promotion/coupons/'+r.id,remove:r=>'/admin/promotion/coupons/'+r.id,fields:[f('name','优惠券名称'),f('discountType','类型 1 每满减 / 2 折扣 / 3 无门槛 / 4 满减','number',3),f('thresholdAmount','门槛（分）','number',0),f('discountValue','减免金额（分）或折扣百分比','number',100),f('maxDiscountAmount','最大优惠（分）','number',0),f('totalNum','库存','number',100),f('userLimit','每人限领','number',1),f('obtainWay','领取方式 1 手领 / 2 兑换','number',1),f('specific','限定范围','boolean',false),f('scopes','适用分类 ID，逗号分隔','ids')]},
 orders:{title:'订单管理',list:'/admin/trade/order-details/page',columns:[['id','条目 ID'],['orderId','订单 ID'],['name','课程'],['realPayAmount','实付（分）'],['statusDesc','状态']]},
 refunds:{title:'退款审核',list:'/admin/trade/refund-apply/page',columns:[['id','退款 ID'],['orderDetailId','条目 ID'],['orderId','订单 ID'],['refundAmount','退款金额（分）'],['proposerName','申请人'],['refundStatusDesc','状态'],['createTime','申请时间']],actions:[{label:'同意退款',path:()=>'/admin/trade/refund-apply/approval',method:'PUT',body:r=>({id:r.id,approveType:1,approveOpinion:'审核通过'})},{label:'拒绝退款',path:()=>'/admin/trade/refund-apply/approval',method:'PUT',body:r=>({id:r.id,approveType:2,approveOpinion:'审核未通过，请联系管理员'})}]},
 templates:{title:'通知模板',list:'/admin/message/notice-templates',columns:[['id','模板 ID'],['intro','说明'],['title','通知标题'],['status','状态']],create:'/admin/message/notice-templates',update:r=>'/admin/message/notice-templates/'+r.id,detail:r=>'/admin/message/notice-templates/'+r.id,fields:[f('name','模板名称'),f('code','模板代码'),f('type','类型 0 系统 / 1 笔记 / 2 问答 / 3 其他','number',0),f('status','状态 0 草稿 / 1 使用 / 2 停用','number',0),f('title','通知标题'),f('content','通知内容','long'),f('isSmsTemplate','短信通知','boolean',false)]},
 notices:{title:'通知任务',list:'/admin/message/notice-tasks',columns:[['id','任务 ID'],['name','任务名称'],['pushTime','执行时间'],['finished','完成']],create:'/admin/message/notice-tasks',update:r=>'/admin/message/notice-tasks/'+r.id,detail:r=>'/admin/message/notice-tasks/'+r.id,fields:[f('name','任务名称'),f('templateId','通知模板 ID'),f('partial','指定用户','boolean',false),f('userIds','接收人 ID（逗号分隔）','ids'),f('pushTime','执行时间','datetime'),f('maxTimes','重复次数上限','number',0),f('interval','重复间隔（分钟）','number',0),f('expireTime','失效时间','datetime')]}
};
