<script setup lang="ts">
import {ref} from 'vue';import {get,write,newKey} from '../../../../packages/shared/src/client';import {useTask,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const task=useTask(),id=ref(''),chapters=ref<Row[]>([]),teachers=ref(''),media=ref<Row>({trailer:false,mediaDuration:1}),subjects=ref<Row>({}),subjectIds=ref('');
async function load(){await task.run(async()=>{chapters.value=await get<Row[]>('/admin/course/courses/catas/'+id.value+'?see=false&withPractice=true');});}
function addChapter(){chapters.value.push({name:'',type:1,index:chapters.value.length+1,sections:[{name:'',type:2}]});}
async function save(){const saved=await task.run(async()=>{const body=chapters.value.map((c,i)=>({...c,index:i+1}));await write('/admin/course/courses/catas/save/'+id.value+'/2','POST',body,newKey());return true;});if(saved){await load();task.message.value='章节已保存';}}
async function saveMedia(){await task.run(async()=>{await write('/admin/course/courses/media/save/'+id.value,'POST',[media.value],newKey());task.message.value='视频关联已保存';});}
async function saveQuestions(){await task.run(async()=>{await write('/admin/course/courses/subjects/save/'+id.value,'POST',[{cataId:subjects.value.cataId,subjectIds:subjectIds.value.split(',').map(x=>x.trim()).filter(Boolean)}],newKey());task.message.value='考试题目关联已保存';});}
async function saveTeachers(){await task.run(async()=>{await write('/admin/course/courses/teachers/save','POST',{id:id.value,teachers:teachers.value.split(',').map(x=>x.trim()).filter(Boolean).map(id=>({id,isShow:true}))},newKey());task.message.value='授课教师已保存';});}
</script><template><section class="card"><h2>课程章节、视频与教师</h2><div class="toolbar"><el-input v-model="id" placeholder="课程 ID"/><el-button @click="load" :disabled="!id">加载章节</el-button><el-button @click="addChapter">新增章</el-button></div><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<article v-for="(chapter,index) in chapters" :key="chapter.id||index" class="card"><div class="toolbar"><el-input v-model="chapter.name" placeholder="章名称"/><small>ID {{chapter.id||'保存后生成'}}</small><el-button @click="chapters.splice(index,1)">删除章</el-button></div><div v-for="(item,sectionIndex) in chapter.sections" :key="item.id||sectionIndex" class="toolbar"><el-input v-model="item.name" placeholder="小节 / 考试名称"/><el-select v-model="item.type" style="width:130px"><el-option label="视频小节" :value="2"/><el-option label="考试" :value="3"/></el-select><small>ID {{item.id||'保存后生成'}}</small><el-button @click="chapter.sections.splice(sectionIndex,1)">移除</el-button></div><el-button @click="chapter.sections.push({name:'',type:2})">新增小节 / 考试</el-button></article><el-button type="primary" @click="save" :disabled="!id || !chapters.length || task.busy.value">保存章节</el-button>
<el-divider/><h3>关联视频</h3><el-form label-width="120px"><el-form-item label="小节 ID"><el-input v-model="media.cataId"/></el-form-item><el-form-item label="媒资 ID"><el-input v-model="media.mediaId"/></el-form-item><el-form-item label="视频名称"><el-input v-model="media.videoName"/></el-form-item><el-form-item label="时长（秒）"><el-input-number v-model="media.mediaDuration" :min="1"/></el-form-item><el-form-item label="允许试看"><el-switch v-model="media.trailer"/></el-form-item><el-button @click="saveMedia" :disabled="!id || task.busy.value">保存视频关联</el-button></el-form>
<el-divider/><h3>关联题库</h3><div class="toolbar"><el-input v-model="subjects.cataId" placeholder="考试小节 ID"/><el-input v-model="subjectIds" placeholder="题目 ID，逗号分隔"/><el-button @click="saveQuestions" :disabled="!id || !subjectIds || task.busy.value">关联题目</el-button></div><h3>授课教师</h3><div class="toolbar"><el-input v-model="teachers" placeholder="教师 ID，逗号分隔，最多 5 人"/><el-button @click="saveTeachers" :disabled="!id || !teachers || task.busy.value">保存授课教师</el-button></div></section></template>