<script setup lang="ts">
import {ref,computed,onMounted} from 'vue';import {useRoute} from 'vue-router';import {ElMessageBox} from 'element-plus';
import {get,write,newKey} from '../../../../packages/shared/src/client';import {useTask,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';import EntityPicker from '../components/EntityPicker.vue';
const route=useRoute(),task=useTask(),id=ref(''),selectedCourse=ref<Row[]>([]),chapters=ref<Row[]>([]),teachers=ref<string[]>([]),teacherRows=ref<Row[]>([]),media=ref<Row>({trailer:false}),mediaRows=ref<Row[]>([]),examSection=ref(''),questionIds=ref<string[]>([]),questionRows=ref<Row[]>([]),relations=ref<Row[]>([]),baseline=ref('');
const sections=computed<Row[]>(()=>chapters.value.flatMap(c=>(c.sections||[]).map((s:Row)=>({...s,label:c.name+' / '+s.name}))));
const videos=computed(()=>sections.value.filter(s=>s.id&&Number(s.type)===2)),exams=computed(()=>sections.value.filter(s=>s.id&&Number(s.type)===3));
const dirty=computed(()=>baseline.value!==JSON.stringify(chapters.value));
async function load(next=id.value){
 if(!next)return;if(id.value && dirty.value){try{await ElMessageBox.confirm('章节有未保存修改，继续会放弃这些修改。','切换课程',{confirmButtonText:'放弃并继续',cancelButtonText:'继续编辑'});}catch{return;}}
 await task.run(async()=>{const [detail,catas,staff,subjects]=await Promise.all([get<Row>('/admin/course/courses/baseInfo/'+next+'?see=false'),get<Row[]>('/admin/course/courses/catas/'+next+'?see=false&withPractice=true'),get<Row[]>('/admin/course/courses/teachers/'+next+'?see=false'),get<Row[]>('/admin/course/courses/subjects/get/'+next)]);
 id.value=next;selectedCourse.value=[detail];chapters.value=catas||[];baseline.value=JSON.stringify(chapters.value);teacherRows.value=staff||[];teachers.value=teacherRows.value.map(x=>String(x.id));relations.value=subjects||[];media.value={trailer:false};mediaRows.value=[];examSection.value='';questionIds.value=[];questionRows.value=[];
 });
}
function addChapter(){chapters.value.push({name:'',type:1,canUpdate:true,index:chapters.value.length+1,sections:[{name:'',type:2,canUpdate:true}]});}
function editable(item:Row){return !item.id || item.canUpdate===true;}
async function save(){const saved=await task.run(async()=>{const body=chapters.value.map((c,i)=>({...c,index:i+1,sections:(c.sections||[]).map((s:Row,j:number)=>({...s,index:j+1}))}));await write('/admin/course/courses/catas/save/'+id.value+'/2','POST',body,newKey());baseline.value=JSON.stringify(chapters.value);return true;});if(saved){await load();task.message.value='章节已保存';}}
function selectVideo(){const s=videos.value.find(x=>String(x.id)===String(media.value.cataId));media.value={cataId:s?.id,mediaId:s?.mediaId,videoName:s?.mediaName,mediaDuration:s?.mediaDuration,trailer:!!s?.trailer};mediaRows.value=s?.mediaId?[{id:s.mediaId,filename:s.mediaName,duration:s.mediaDuration}]:[];}
function selectMedia(rows:Row[]){const row=rows[0];media.value.videoName=row?.filename;media.value.mediaDuration=row?Math.ceil(Number(row.duration)):undefined;}
async function saveMedia(){await task.run(async()=>{await write('/admin/course/courses/media/save/'+id.value,'POST',[media.value],newKey());const section=chapters.value.flatMap(c=>c.sections||[]).find((s:Row)=>String(s.id)===String(media.value.cataId));if(section){section.mediaId=media.value.mediaId;section.mediaName=media.value.videoName;section.mediaDuration=media.value.mediaDuration;section.trailer=media.value.trailer;}baseline.value=JSON.stringify(chapters.value);task.message.value='视频关联已保存';});}
function selectExam(){questionRows.value=relations.value.find(x=>String(x.cataId)===examSection.value)?.subjects||[];questionIds.value=questionRows.value.map(x=>String(x.id));}
async function saveQuestions(){await task.run(async()=>{await write('/admin/course/courses/subjects/save/'+id.value,'POST',[{cataId:examSection.value,subjectIds:questionIds.value}],newKey());relations.value=await get<Row[]>('/admin/course/courses/subjects/get/'+id.value);task.message.value='考试题目关联已保存';});}
async function saveTeachers(){await task.run(async()=>{await write('/admin/course/courses/teachers/save','POST',{id:id.value,teachers:teachers.value.map(id=>({id,isShow:true}))},newKey());task.message.value='授课教师已保存';});}
onMounted(()=>{if(route.query.courseId)void load(String(route.query.courseId));});
</script>
<template><section class="card"><h2>课程章节、视频与教师</h2><p class="muted">选择待上架或已下架草稿进行配置。已上架课程请先在课程管理下架；已发布章节的修改限制仍由服务端校验。</p>
<div class="toolbar"><EntityPicker :model-value="id" :selected-rows="selectedCourse" kind="courses" :course-statuses="[1,3]" label="选择配置课程" :disabled="task.busy.value" @update:model-value="load(String($event))"/><el-button @click="addChapter" :disabled="!id || task.busy.value">新增章</el-button></div><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<template v-if="id">
<article v-for="(chapter,index) in chapters" :key="chapter.id||index" class="card chapter-editor"><div class="toolbar"><el-input v-model="chapter.name" placeholder="章名称" :disabled="!editable(chapter)"/><el-button @click="chapters.splice(index,1)" :disabled="!editable(chapter)">删除章</el-button><small v-if="!editable(chapter)" class="muted">已发布章节</small></div>
<div v-for="(item,sectionIndex) in chapter.sections" :key="item.id||sectionIndex" class="toolbar"><el-input v-model="item.name" placeholder="小节 / 考试名称" :disabled="!editable(item)"/><el-select v-model="item.type" style="width:130px" :disabled="!editable(item)"><el-option label="视频小节" :value="2"/><el-option label="考试" :value="3"/></el-select><el-button @click="chapter.sections.splice(sectionIndex,1)" :disabled="!editable(item)">移除</el-button></div><el-button @click="chapter.sections.push({name:'',type:2,canUpdate:true})">新增小节 / 考试</el-button></article>
<el-empty v-if="!chapters.length" description="尚未创建课程目录，请先新增章"/><el-button type="primary" @click="save" :disabled="!chapters.length || chapters.some(c=>!c.name.trim() || !c.sections?.length || c.sections.some((s:Row)=>!s.name.trim())) || task.busy.value">保存章节</el-button>
<el-divider/><h3>关联视频</h3><p class="muted">请先保存目录，再选择已登记的视频。名称与时长来自真实媒资记录，无须手工复制编号。</p><el-form label-position="top"><div class="grid"><el-form-item label="视频小节"><el-select v-model="media.cataId" aria-label="选择视频小节" @change="selectVideo"><el-option v-for="s in videos" :key="s.id" :value="s.id" :label="s.label"/></el-select></el-form-item><el-form-item label="课程视频"><EntityPicker v-model="media.mediaId" kind="media" label="选择课程视频" :selected-rows="mediaRows" :disabled="!media.cataId || task.busy.value" @change="selectMedia"/></el-form-item><el-form-item label="允许试看"><el-switch v-model="media.trailer"/></el-form-item></div><p v-if="media.mediaId" class="muted">{{media.videoName}} · {{media.mediaDuration}} 秒</p><el-button @click="saveMedia" :disabled="!media.cataId || !media.mediaId || !media.mediaDuration || dirty || task.busy.value">保存视频关联</el-button></el-form>
<el-divider/><h3>关联题库</h3><div class="toolbar"><el-select v-model="examSection" aria-label="选择关联考试小节" placeholder="选择考试小节" @change="selectExam"><el-option v-for="s in exams" :key="s.id" :value="String(s.id)" :label="s.label"/></el-select></div><EntityPicker v-model="questionIds" kind="questions" label="选择关联题目" multiple :selected-rows="questionRows" :disabled="!examSection || task.busy.value" @change="questionRows=$event"/><el-button @click="saveQuestions" :disabled="!examSection || !questionIds.length || dirty || task.busy.value">关联题目</el-button>
<el-divider/><h3>授课教师</h3><EntityPicker v-model="teachers" kind="teachers" label="选择授课教师" multiple :limit="5" :selected-rows="teacherRows" :disabled="task.busy.value"/><el-button @click="saveTeachers" :disabled="!teachers.length || dirty || task.busy.value">保存授课教师</el-button>
</template></section></template>
