<script setup lang="ts">
import {ref,onMounted,computed} from 'vue';import {get} from '../../../../packages/shared/src/client';import {useTask,money,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const task=useTask(),data=ref<Row>({}),table=ref(false);const labels:Record<string,string>={createdOrders:'今日创建订单',paidAmount:'今日已支付订单金额',refundAmount:'今日退款金额',openConflicts:'待处理支付工单',pendingEvents:'交易事件积压'};
function displayTime(value:unknown,dateOnly=false){if(typeof value!=='string' || !value)return '未加载';const time=new Date(value);if(Number.isNaN(time.valueOf()))return value;const options:Intl.DateTimeFormatOptions={timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',...(dateOnly?{}:{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})};return new Intl.DateTimeFormat('zh-CN',options).format(time).replaceAll('/','-');}
const days=computed<Row[]>(()=>[...(data.value.orderDays||[])].sort((a,b)=>String(a.day).localeCompare(String(b.day))));
const highest=computed(()=>Math.max(1,...days.value.map(d=>Number(d.orders))));
async function load(){await task.run(async()=>{data.value=await get<Row>('/admin/dashboard');});}onMounted(load);
</script>
<template><section class="dashboard-page"><div class="dashboard-welcome"><div><p class="eyebrow">教学管理工作台</p><h2>今天的工作，从这里开始。</h2><p class="muted">关注教学进展，也关注每一笔交易的结果。</p></div><el-button @click="load" :disabled="task.busy.value">刷新数据</el-button></div><Status :busy="task.busy.value" :error="task.error.value"/><p class="muted update-time">更新时间 {{displayTime(data.updatedAt)}} · 以下数据来自当前部署</p>
<div class="dashboard-stats"><article v-for="(label,key,i) in labels" :key="key" class="card metric-card"><span class="metric-mark" :class="'metric-'+i">{{['单','¥','退','!','↗'][i]}}</span><p>{{label}}</p><strong class="stat">{{data[key]===undefined?'未加载':key==='paidAmount'||key==='refundAmount'?money(data[key]):data[key]}}</strong></article></div>
<div class="dashboard-columns"><section class="card"><div class="section-heading"><div><h2>订单趋势</h2><p class="muted">近 30 天 · 每日创建订单数</p></div><el-button text @click="table=!table">{{table?'收起明细':'查看明细'}}</el-button></div><div v-if="days.length" class="trend-chart" role="img" aria-label="近30天每日订单数量柱状图"><div class="chart-bars"><div v-for="day in days" :key="day.day" class="chart-column" :title="displayTime(day.day,true)+'：'+day.orders+' 笔订单'"><span>{{day.orders}}</span><div class="chart-bar" :style="{height:Math.max(3,Number(day.orders)/highest*180)+'px'}"></div><small>{{displayTime(day.day,true).slice(5)}}</small></div></div><p class="muted">只展示有订单的数据日期；完整数值可在明细中查看。</p></div><el-empty v-else-if="!task.busy.value" description="暂无订单趋势数据"/><el-table v-if="table" :data="days"><el-table-column label="日期" min-width="130"><template #default="{row}">{{displayTime(row.day,true)}}</template></el-table-column><el-table-column prop="orders" label="创建订单"/><el-table-column label="当前已支付订单金额" min-width="180"><template #default="{row}">{{money(row.paid_amount)}}</template></el-table-column></el-table></section>
<aside><section class="card quick-actions"><h2>常用功能</h2><div class="quick-action-grid"><RouterLink to="/courses"><span aria-hidden="true">▤</span>课程管理</RouterLink><RouterLink to="/exams"><span aria-hidden="true">✓</span>试卷与评分</RouterLink><RouterLink to="/orders"><span aria-hidden="true">▧</span>订单管理</RouterLink><RouterLink to="/refunds"><span aria-hidden="true">↩</span>退款审核</RouterLink></div></section><section class="card attention-card"><p class="eyebrow">需要关注</p><h2>交易与事件</h2><p>待处理支付工单 <strong>{{data.openConflicts??'—'}}</strong></p><p>交易事件积压 <strong>{{data.pendingEvents??'—'}}</strong></p><p class="muted">取消后到账的款项单独进入支付冲突工单。</p><RouterLink to="/reliability">查看失败与补偿任务 →</RouterLink></section></aside></div></section></template>
