<script setup lang="ts">
import {ref} from 'vue';import {useSession} from '../../../../packages/shared/src/session';const session=useSession();import {get} from '../../../../packages/shared/src/client';import {useOperations} from '../../../../packages/shared/src/operations';import {useTask,examStatus,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const task=useTask(),ops=useOperations(),course=ref(''),section=ref(''),ids=ref(''),graders=ref(''),percent=ref(60),pending=ref<Row[]>([]),attempt=ref<Row>(),scores=ref<Record<string,number>>({}),feedback=ref<Record<string,string>>({});
const list=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
async function publish(){await task.run(async()=>{const result=await ops.begin('exam','发布新试卷版本','/admin/exam-papers',{courseId:course.value,sectionId:section.value,questionIds:list(ids.value),passPercent:percent.value,graders:list(graders.value)});task.message.value=result.status==='SUCCEEDED'?'试卷版本已发布':'试卷发布处理中';});}
async function load(){await task.run(async()=>{pending.value=await get<Row[]>('/teacher/exam-attempts');});}
async function view(id:string){await task.run(async()=>{attempt.value=await get<Row>('/teacher/exam-attempts/'+id);scores.value={};feedback.value={};});}
async function grade(answer:Row){await task.run(async()=>{if(!attempt.value)return;const result=await ops.begin('exam','教师评分','/teacher/exam-attempts/'+attempt.value.id+'/grades',{questionId:answer.question_id,score:scores.value[answer.question_id]??0,version:answer.version,feedback:feedback.value[answer.question_id]||''});if(result.status==='SUCCEEDED')attempt.value=await get<Row>('/teacher/exam-attempts/'+attempt.value.id);});}
</script><template><section class="card"><h2>试卷版本与教师评分</h2><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<el-form v-if="session.role===1" label-position="top"><div class="grid"><el-form-item label="课程 ID"><el-input v-model="course"/></el-form-item><el-form-item label="考试小节 ID"><el-input v-model="section"/></el-form-item><el-form-item label="题目 ID，逗号分隔"><el-input v-model="ids"/></el-form-item><el-form-item label="评分教师 ID，逗号分隔"><el-input v-model="graders"/></el-form-item><el-form-item label="及格百分比"><el-input-number v-model="percent" :min="1" :max="100"/></el-form-item></div><el-button type="primary" @click="publish" :disabled="!course || !section || !ids || task.busy.value">发布不可变试卷版本</el-button></el-form>
<h3>待评分考试</h3><el-button @click="load">刷新待评分列表</el-button><el-table :data="pending"><el-table-column prop="id" label="考试记录"/><el-table-column prop="user_id" label="学生"/><el-table-column prop="course_id" label="课程"/><el-table-column label="操作"><template #default="{row}"><el-button @click="view(row.id)">查看答卷</el-button></template></el-table-column></el-table>
<article v-if="attempt"><h3>考试 {{attempt.id}} · {{examStatus(attempt.status)}}</h3><div v-for="answer in attempt.answers" :key="answer.question_id" class="section"><h4>{{attempt.questions.find((q:Row)=>q.question_id===answer.question_id)?.name}}</h4><p class="content">{{answer.response}}</p><p v-if="answer.score!==null">已评分 {{answer.score}} · {{answer.feedback}}</p><template v-else><el-input-number v-model="scores[answer.question_id]" :min="0" :max="attempt.questions.find((q:Row)=>q.question_id===answer.question_id)?.score||0"/><el-input v-model="feedback[answer.question_id]" placeholder="评分反馈"/><el-button @click="grade(answer)" :disabled="task.busy.value">提交评分</el-button></template></div></article></section></template>