<script setup lang="ts">
import {ref} from 'vue';import {get,write} from '../../../../packages/shared/src/client';import {useTask,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const task=useTask(),service=ref('trade'),events=ref<Row[]>([]),failures=ref<Row[]>([]),conflicts=ref<Row[]>([]),resolution=ref(''),selected=ref<Row>(),compensationKind=ref('payment'),compensations=ref<Row[]>([]),deliveryKind=ref('notice'),deliveries=ref<Row[]>([]),cleanups=ref<Row[]>([]),metadata=ref<Row[]>([]),operations=ref<Row[]>([]);
const services=['trade','learning','promotion','exam','search','remark','message','user','course','media','pay'];
async function load(){await task.run(async()=>{const [e,f,c,t,o]=await Promise.all([get<Row[]>('/admin/events/'+service.value+'/failures'),get<Row[]>('/admin/consumer-failures/'+service.value),get<Row[]>('/admin/payment-conflicts'),get<Row[]>('/admin/compensations/'+compensationKind.value),get<Row[]>('/admin/operation-failures/'+service.value)]);events.value=e;failures.value=f;conflicts.value=c;compensations.value=t;operations.value=o;});}
async function replay(row:Row,consumer:boolean){const ok=await task.run(async()=>{await write(consumer?'/admin/consumer-failures/'+service.value+'/'+row.failure_id+'/replay?version='+row.version:'/admin/events/'+service.value+'/'+row.event_id+'/replay','POST');return true;});if(ok){await load();task.message.value='已安排重放，事件 ID 保持不变';}}
async function replayCompensation(row:Row){const ok=await task.run(async()=>{await write('/admin/compensations/'+compensationKind.value+'/'+(row.refund_id??row.order_id)+'/replay?version='+row.version,'POST');return true;});if(ok){await load();task.message.value='已安排补偿重试';}}
async function loadDeliveries(){await task.run(async()=>{deliveries.value=await get<Row[]>('/admin/deliveries/'+deliveryKind.value);});}
async function replayDelivery(row:Row){const ok=await task.run(async()=>{await write('/admin/deliveries/'+deliveryKind.value+'/'+row.id+'/replay?version='+row.version,'POST');return true;});if(ok)await loadDeliveries();}
async function loadProjections(){await task.run(async()=>{[cleanups.value,metadata.value]=await Promise.all([get<Row[]>('/admin/storage-cleanups'),get<Row[]>('/admin/search-projections')]);});}
async function replayProjection(row:Row,storage:boolean){const ok=await task.run(async()=>{await write((storage?'/admin/storage-cleanups/':'/admin/search-projections/')+(row.id??row.course_id)+'/replay?version='+row.version+(storage?'':'&kind='+row.kind),'POST');return true;});if(ok)await loadProjections();}
async function replayOperation(row:Row){const ok=await task.run(async()=>{await write('/admin/operation-failures/'+service.value+'/'+row.operation_id+'/replay?version='+row.version,'POST');return true;});if(ok)await load();}
async function resolve(){const ok=await task.run(async()=>{if(!selected.value)return;await write('/admin/payment-conflicts/'+selected.value.id,'PUT',{version:selected.value.version,resolution:resolution.value});selected.value=undefined;return true;});if(ok){await load();task.message.value='人工处理依据已记录';}}
</script><template><section class="card"><h2>事件与业务冲突处理</h2><div class="toolbar"><el-select v-model="service" style="width:180px"><el-option v-for="s in services" :key="s" :value="s" :label="s"/></el-select><el-button @click="load">查询服务</el-button></div><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<h3>业务请求失败</h3><el-table :data="operations"><el-table-column prop="operation_id" label="操作 ID"/><el-table-column prop="kind" label="类型"/><el-table-column prop="last_error" label="失败原因"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.error_code==='RETRY_EXHAUSTED'" @click="replayOperation(row)">重试临时故障</el-button><span v-else>业务校验失败，请修正请求</span></template></el-table-column></el-table>
<h3>投递失败任务</h3><el-table :data="events"><el-table-column prop="event_id" label="事件 ID"/><el-table-column prop="business_key" label="业务标识"/><el-table-column prop="attempts" label="尝试次数"/><el-table-column prop="last_error" label="失败原因"/><el-table-column label="操作"><template #default="{row}"><el-button @click="replay(row,false)" :disabled="task.busy.value">重放</el-button></template></el-table-column></el-table>
<h3>消费失败任务</h3><el-table :data="failures"><el-table-column prop="event_id" label="事件 ID"/><el-table-column prop="queue_name" label="消费队列"/><el-table-column prop="last_error" label="失败原因"/><el-table-column label="操作"><template #default="{row}"><el-button @click="replay(row,true)" :disabled="task.busy.value">重放</el-button></template></el-table-column></el-table>
<h3>持久补偿任务</h3><div class="toolbar"><el-select v-model="compensationKind" @change="load"><el-option value="payment" label="支付核对"/><el-option value="refund" label="退款发送"/></el-select></div><el-table :data="compensations"><el-table-column label="业务 ID"><template #default="{row}">{{row.refund_id??row.order_id}}</template></el-table-column><el-table-column prop="status" label="状态"/><el-table-column prop="attempts" label="尝试次数"/><el-table-column prop="last_error" label="失败原因"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.status==='DEAD'" @click="replayCompensation(row)" :disabled="task.busy.value">重试失败任务</el-button></template></el-table-column></el-table>
<h3>通知发送任务</h3><div class="toolbar"><el-select v-model="deliveryKind"><el-option value="notice" label="站内通知"/><el-option value="sms" label="短信发送"/></el-select><el-button @click="loadDeliveries">查询通知任务</el-button></div><el-table :data="deliveries"><el-table-column prop="id" label="任务 ID"/><el-table-column prop="status" label="状态"/><el-table-column prop="last_error" label="失败原因"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.status==='DEAD'" @click="replayDelivery(row)">重试失败任务</el-button></template></el-table-column></el-table>
<h3>资源删除与搜索投影</h3><el-button @click="loadProjections">查询资源与搜索任务</el-button><el-table :data="[...cleanups.map(x=>({...x,storage:true})),...metadata.map(x=>({...x,storage:false}))]"><el-table-column label="业务 ID"><template #default="{row}">{{row.id??row.course_id}}</template></el-table-column><el-table-column prop="status" label="状态"/><el-table-column prop="last_error" label="失败原因"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.status==='DEAD'" @click="replayProjection(row,row.storage)">重试失败任务</el-button></template></el-table-column></el-table>
<h3>支付冲突工单</h3><p>取消后到账的支付事实保留在工单中。确认处理依据不会自动恢复订单、发课或退款。</p><el-table :data="conflicts"><el-table-column prop="order_id" label="订单 ID"/><el-table-column prop="pay_order_no" label="支付单号"/><el-table-column prop="reason" label="冲突原因"/><el-table-column label="操作"><template #default="{row}"><el-button @click="selected=row;resolution=''">记录人工处理</el-button></template></el-table-column></el-table>
<el-dialog :model-value="!!selected" @update:model-value="(value:boolean)=>{if(!value)selected=undefined;}" title="记录人工处理依据"><Status :busy="task.busy.value" :error="task.error.value"/><el-input v-model="resolution" type="textarea" :rows="6" maxlength="2000"/><template #footer><el-button type="primary" @click="resolve" :disabled="!resolution.trim() || task.busy.value">保存处理记录</el-button></template></el-dialog></section></template>
