<script setup lang="ts">
import {ref,computed,watch,onMounted} from 'vue';import {get,write,newKey} from '../../../../packages/shared/src/client';import {useTask,query,money,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';import {resources,type Action} from '../resources';
import {useOperations} from '../../../../packages/shared/src/operations';import LocalUpload from './LocalUpload.vue';import CourseForm from '../components/CourseForm.vue';
const ops=useOperations();
const props=defineProps<{resource:string}>(),schema=computed(()=>resources[props.resource]!),task=useTask(),rows=ref<Row[]>([]),page=ref(1),total=ref(0),keyword=ref(''),courseStatus=ref<number|undefined>(2),form=ref<Row>(),original=ref<Row>(),key=ref('');
const enrollmentEnded=(row:Row)=>!!row.purchaseEndTime && new Date(row.purchaseEndTime).getTime()<=Date.now();
async function load(){await task.run(async()=>{const result=await get<Row|Row[]>(schema.value.list+'?'+query({pageNo:page.value,pageSize:20,name:['courses','questions'].includes(props.resource)?undefined:keyword.value,keyword:['courses','questions'].includes(props.resource)?keyword.value:undefined,status:props.resource==='courses'?courseStatus.value:undefined}));rows.value=Array.isArray(result)?result:result.list||[];total.value=Array.isArray(result)?result.length:Number(result.total||0);});}
async function edit(row?:Row){await task.run(async()=>{original.value=row;const value=row && schema.value.detail?await get<Row>(schema.value.detail(row)):{...row};const model:Row={};for(const field of schema.value.fields||[]){let v=value[field.key]??field.initial??'';if(field.kind==='ids' && Array.isArray(v))v=v.join(',');if(field.kind==='options' && Array.isArray(v))v=v.join('\n');model[field.key]=v;}if(row){model.id=row.id;if(props.resource==='courses')model.purchaseStartTime=value.purchaseStartTime;}form.value=model;key.value=newKey();});}
async function save(){const saved=await task.run(async()=>{if(!form.value)return;const body={...form.value};for(const field of schema.value.fields||[]){if(field.kind==='ids')body[field.key]=String(body[field.key]||'').split(',').map(x=>x.trim()).filter(Boolean);if(field.kind==='options')body[field.key]=String(body[field.key]||'').split('\n').filter(Boolean);}const path=original.value?schema.value.update?.(original.value):schema.value.create;if(!path)throw new Error('此资源不支持该操作');if(props.resource==='notices' && !original.value){const result=await ops.begin('message','创建通知任务',path,body,'POST');if(result.status!=='SUCCEEDED'){task.message.value='任务正在创建，可在操作记录中查询';return false;}}else await write(path,original.value && props.resource!=='courses'?'PUT':'POST',body,key.value);form.value=undefined;return true;});if(saved){await load();task.message.value='保存成功';}}
async function saveCourse(body:Row){const saved=await task.run(async()=>{await write('/admin/course/courses/baseInfo/save','POST',body,key.value);form.value=undefined;courseStatus.value=original.value?Number(original.value.status):1;return true;});if(saved){await load();task.message.value='课程资料已保存';}}
async function action(row:Row,item:Action){const completed=await task.run(async()=>{if(props.resource==='refunds'){const result=await ops.begin('trade',item.label,item.path(row),item.body?.(row),item.method);if(result.status!=='SUCCEEDED'){task.message.value='正在处理，可在操作记录中查询';return false;}}else await write(item.path(row),item.method,item.body?.(row),newKey());return true;});if(completed){if(props.resource==='courses'){courseStatus.value=item.label==='下架'?3:2;keyword.value=row.name;page.value=1;}await load();task.message.value=item.label+'已完成';}}
async function remove(row:Row){const removed=await task.run(async()=>{if(props.resource==='media'){const result=await ops.begin('media','删除视频',schema.value.remove!(row),undefined,'DELETE');if(result.status!=='SUCCEEDED'){task.message.value='正在处理，可在操作记录中查询';return false;}}else await write(schema.value.remove!(row),'DELETE',undefined,newKey());return true;});if(removed)await load();}
watch(()=>props.resource,()=>{page.value=1;form.value=undefined;void load();});onMounted(load);
</script>
<template><section class="card"><h2>{{schema.title}}</h2><div class="toolbar"><el-select v-if="resource==='courses'" v-model="courseStatus" style="width:140px" :disabled="task.busy.value" aria-label="课程状态" @change="page=1;load()"><el-option label="待上架草稿" :value="1"/><el-option label="已上架" :value="2"/><el-option label="已下架草稿" :value="3"/><el-option label="已完结" :value="4"/></el-select><el-input v-model="keyword" placeholder="按名称搜索" @keyup.enter="page=1;load()"/><el-button :disabled="task.busy.value" @click="page=1;load()">查询</el-button><el-button v-if="schema.create" type="primary" :disabled="task.busy.value" @click="edit()">新增</el-button><RouterLink v-if="resource==='courses'" to="/course-editor">章节与教师配置</RouterLink><RouterLink v-if="resource==='coupons'" to="/coupon-issue">发放优惠券</RouterLink></div><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<el-alert v-if="resource==='courses' && [2,4].includes(Number(courseStatus))" title="已上架课程的资料不可直接修改。需要更新时先下架，修改草稿并确认报名计划后再重新上架。" type="info" :closable="false"/><LocalUpload v-if="resource==='media'" @saved="load"/><el-table :data="rows"><el-table-column v-for="[field,label] in schema.columns" :key="field" :prop="field" :label="label"><template #default="{row}"><span v-if="resource==='courses' && field==='price'">{{money(row.price)}}</span><span v-else-if="resource==='courses' && field==='status'">{{({1:'待上架',2:'已上架',3:'已下架',4:'已完结'} as Record<number,string>)[row.status]}}</span><span v-else-if="resource==='courses' && field==='purchaseEndTime'">{{row[field]}}<el-tag v-if="enrollmentEnded(row)" type="warning" size="small">报名结束</el-tag></span><span v-else>{{row[field]}}</span></template></el-table-column><el-table-column label="操作" min-width="220"><template #default="{row}"><el-button v-if="schema.update" :disabled="task.busy.value || resource==='courses' && ![1,3].includes(Number(row.status))" @click="edit(row)">编辑</el-button><RouterLink v-if="resource==='courses' && [1,3].includes(Number(row.status))" :to="'/course-editor?courseId='+row.id">配置章节</RouterLink><el-popconfirm v-if="schema.remove" title="确认删除这条记录？" @confirm="remove(row)"><template #reference><el-button>删除</el-button></template></el-popconfirm><el-popconfirm v-for="item in schema.actions" :key="item.label" :title="'确认'+item.label+'？'" @confirm="action(row,item)"><template #reference><el-button :disabled="task.busy.value || resource==='refunds' && Number(row.status)!==1 || resource==='courses' && (item.label==='上架'?(![1,3].includes(Number(row.status)) || enrollmentEnded(row)):Number(row.status)!==2)">{{item.label}}</el-button></template></el-popconfirm></template></el-table-column></el-table><el-pagination v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next" @current-change="load"/>
<el-dialog :model-value="!!form" @update:model-value="(value:boolean)=>{if(!value)form=undefined;}" :title="original?'编辑记录':'新增记录'"><Status :error="task.error.value" :busy="task.busy.value"/><CourseForm :key="key" v-if="form && resource==='courses'" :model-value="form" :busy="task.busy.value" @save="saveCourse" @cancel="form=undefined"/><el-form v-else-if="form" label-position="top"><el-form-item v-for="field in schema.fields" :key="field.key" :label="field.label"><el-input-number v-if="field.kind==='number'" v-model="form[field.key]" :min="0"/><el-switch v-else-if="field.kind==='boolean'" v-model="form[field.key]"/><el-date-picker v-else-if="field.kind==='datetime'" v-model="form[field.key]" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/><el-input v-else v-model="form[field.key]" :type="['long','options'].includes(field.kind||'')?'textarea':'text'" :rows="4"/></el-form-item></el-form><template v-if="resource!=='courses'" #footer><el-button @click="form=undefined">取消</el-button><el-button type="primary" @click="save" :disabled="task.busy.value">保存</el-button></template></el-dialog></section></template>
