<script setup lang="ts">
import {ref,computed,watch,onMounted} from 'vue';import {get,write,newKey} from '../../../../packages/shared/src/client';import {useTask,query,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';import {resources,type Action} from '../resources';
import {useOperations} from '../../../../packages/shared/src/operations';import LocalUpload from './LocalUpload.vue';
const ops=useOperations();
const props=defineProps<{resource:string}>(),schema=computed(()=>resources[props.resource]!),task=useTask(),rows=ref<Row[]>([]),page=ref(1),total=ref(0),keyword=ref(''),courseStatus=ref<number|undefined>(2),form=ref<Row>(),original=ref<Row>(),key=ref('');
async function load(){await task.run(async()=>{const result=await get<Row|Row[]>(schema.value.list+'?'+query({pageNo:page.value,pageSize:20,name:keyword.value,status:props.resource==='courses'?courseStatus.value:undefined}));rows.value=Array.isArray(result)?result:result.list||[];total.value=Array.isArray(result)?result.length:Number(result.total||0);});}
async function edit(row?:Row){await task.run(async()=>{original.value=row;const value=row && schema.value.detail?await get<Row>(schema.value.detail(row)):{...row};const model:Row={};for(const field of schema.value.fields||[]){let v=value[field.key]??field.initial??'';if(field.kind==='ids' && Array.isArray(v))v=v.join(',');if(field.kind==='options' && Array.isArray(v))v=v.join('\n');model[field.key]=v;}if(row)model.id=row.id;form.value=model;key.value=newKey();});}
async function save(){const saved=await task.run(async()=>{if(!form.value)return;const body={...form.value};for(const field of schema.value.fields||[]){if(field.kind==='ids')body[field.key]=String(body[field.key]||'').split(',').map(x=>x.trim()).filter(Boolean);if(field.kind==='options')body[field.key]=String(body[field.key]||'').split('\n').filter(Boolean);}const path=original.value?schema.value.update?.(original.value):schema.value.create;if(!path)throw new Error('此资源不支持该操作');if(props.resource==='notices' && !original.value){const result=await ops.begin('message','创建通知任务',path,body,'POST');if(result.status!=='SUCCEEDED'){task.message.value='任务正在创建，可在操作记录中查询';return false;}}else await write(path,original.value && props.resource!=='courses'?'PUT':'POST',body,key.value);form.value=undefined;return true;});if(saved){await load();task.message.value='保存成功';}}
async function action(row:Row,item:Action){const completed=await task.run(async()=>{if(props.resource==='refunds'){const result=await ops.begin('trade',item.label,item.path(row),item.body?.(row),item.method);if(result.status!=='SUCCEEDED'){task.message.value='正在处理，可在操作记录中查询';return false;}}else await write(item.path(row),item.method,item.body?.(row),newKey());return true;});if(completed){await load();task.message.value=item.label+'已完成';}}
async function remove(row:Row){const removed=await task.run(async()=>{if(props.resource==='media'){const result=await ops.begin('media','删除视频',schema.value.remove!(row),undefined,'DELETE');if(result.status!=='SUCCEEDED'){task.message.value='正在处理，可在操作记录中查询';return false;}}else await write(schema.value.remove!(row),'DELETE',undefined,newKey());return true;});if(removed)await load();}
watch(()=>props.resource,()=>{page.value=1;form.value=undefined;void load();});onMounted(load);
</script>
<template><section class="card"><h2>{{schema.title}}</h2><div class="toolbar"><el-select v-if="resource==='courses'" v-model="courseStatus" style="width:140px" aria-label="课程状态" @change="page=1;load()"><el-option label="待上架草稿" :value="1"/><el-option label="已上架" :value="2"/><el-option label="已下架草稿" :value="3"/><el-option label="已完结" :value="4"/></el-select><el-input v-model="keyword" placeholder="按名称搜索" @keyup.enter="page=1;load()"/><el-button @click="page=1;load()">查询</el-button><el-button v-if="schema.create" type="primary" @click="edit()">新增</el-button><RouterLink v-if="resource==='courses'" to="/course-editor">章节与教师配置</RouterLink><RouterLink v-if="resource==='coupons'" to="/coupon-issue">发放优惠券</RouterLink></div><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<LocalUpload v-if="resource==='media'" @saved="load"/><el-table :data="rows"><el-table-column v-for="[field,label] in schema.columns" :key="field" :prop="field" :label="label"/><el-table-column label="操作" min-width="220"><template #default="{row}"><el-button v-if="schema.update" @click="edit(row)">编辑</el-button><el-popconfirm v-if="schema.remove" title="确认删除这条记录？" @confirm="remove(row)"><template #reference><el-button>删除</el-button></template></el-popconfirm><el-popconfirm v-for="item in schema.actions" :key="item.label" :title="'确认'+item.label+'？'" @confirm="action(row,item)"><template #reference><el-button :disabled="task.busy.value || resource==='refunds' && Number(row.status)!==1">{{item.label}}</el-button></template></el-popconfirm></template></el-table-column></el-table><el-pagination v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next" @current-change="load"/>
<el-dialog :model-value="!!form" @update:model-value="(value:boolean)=>{if(!value)form=undefined;}" :title="original?'编辑记录':'新增记录'"><Status :error="task.error.value" :busy="task.busy.value"/><el-form v-if="form" label-position="top"><el-form-item v-for="field in schema.fields" :key="field.key" :label="field.label"><el-input-number v-if="field.kind==='number'" v-model="form[field.key]" :min="0"/><el-switch v-else-if="field.kind==='boolean'" v-model="form[field.key]"/><el-date-picker v-else-if="field.kind==='datetime'" v-model="form[field.key]" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/><el-input v-else v-model="form[field.key]" :type="['long','options'].includes(field.kind||'')?'textarea':'text'" :rows="4"/></el-form-item></el-form><template #footer><el-button @click="form=undefined">取消</el-button><el-button type="primary" @click="save" :disabled="task.busy.value">保存</el-button></template></el-dialog></section></template>
