<script setup lang="ts">
import {ref,onMounted} from 'vue';import {get,write,newKey} from '../../../../packages/shared/src/client';import {useTask,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const task=useTask(),roles=ref<Row[]>([]),roleId=ref(''),privileges=ref<Row[]>([]),selected=ref<string[]>([]),original=ref<string[]>([]),notice=ref(''),page=ref(1),total=ref(0);
async function load(){if(!roleId.value)return;const ids=await get<string[]>('/admin/auth/privileges/role/'+roleId.value);original.value=ids.map(String);selected.value=[...original.value];}
async function save(){if(!roleId.value)return;const add=selected.value.filter(id=>!original.value.includes(id)),remove=original.value.filter(id=>!selected.value.includes(id));for(let i=0;i<add.length;i+=100)await write('/admin/auth/privileges/role/'+roleId.value,'POST',add.slice(i,i+100),newKey());for(let i=0;i<remove.length;i+=100)await write('/admin/auth/privileges/role/'+roleId.value,'DELETE',remove.slice(i,i+100),newKey());await load();notice.value='权限已保存，缓存发布任务正在同步';}
async function loadPage(){const result=await get<{list:Row[];total:number}>('/admin/auth/privileges?pageSize=20&pageNo='+page.value);privileges.value=result.list;total.value=Number(result.total);}
onMounted(()=>task.run(async()=>{roles.value=await get('/admin/auth/roles/list');await loadPage();}));
</script>
<template><section class="card"><h2>角色接口权限</h2><Status :busy="task.busy.value" :error="task.error.value"/><el-alert v-if="notice" :title="notice" type="success"/><el-select :disabled="task.busy.value" v-model="roleId" placeholder="选择角色" @change="task.run(load)"><el-option v-for="role in roles" :key="role.id" :value="String(role.id)" :label="role.name"/></el-select><el-checkbox-group v-model="selected"><div v-for="p in privileges" :key="p.id"><el-checkbox :value="String(p.id)" :disabled="!roleId || p.internal">{{p.intro}} · {{p.method}} {{p.uri}}</el-checkbox></div></el-checkbox-group><el-pagination v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next" @current-change="task.run(loadPage)"/><el-button type="primary" :disabled="!roleId || task.busy.value" @click="task.run(save)">保存角色权限</el-button><p>每页 20 条，跨页选择会保留。内部接口保持由服务身份验证；权限缓存通过持久事件发布。</p></section></template>
