CREATE TABLE IF NOT EXISTS exam_draft(
 attempt_id BIGINT PRIMARY KEY,
 answers LONGTEXT NOT NULL,
 version BIGINT NOT NULL DEFAULT 0,
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
