<script setup lang="ts">
import {ref,onMounted} from 'vue';import {get} from '../../../../packages/shared/src/client';import {useTask,money,query,type Row} from '../../../../packages/shared/src/ui';import type {components} from '../../../../packages/shared/src/generated/search';import Status from '../../../../packages/shared/src/Status.vue';
type Course=components['schemas']['CourseVO'];type CoursePage=components['schemas']['PageDTOCourseVO'];
const failedCovers=ref(new Set<string>()),task=useTask(),keyword=ref(''),page=ref(1),rows=ref<Course[]>([]),total=ref(0),sort=ref(''),categories=ref<Row[]>([]),category=ref(''),free=ref(''),categoryError=ref('');
async function load(){await task.run(async()=>{const result=await get<CoursePage>('/services/search/courses/portal?'+query({keyword:keyword.value,pageNo:page.value,pageSize:20,sortBy:sort.value,categoryIdLv1:category.value,free:free.value}));rows.value=result.list||[];total.value=Number(result.total||0);});}
function filterCategory(id:string){category.value=id;page.value=1;void load();}
function reset(){keyword.value='';category.value='';free.value='';sort.value='';page.value=1;void load();}
onMounted(async()=>{void load();try{categories.value=await get<Row[]>('/services/course/categorys/list?status=1');}catch{categoryError.value='课程分类暂时无法加载，仍可搜索课程。';}});
</script>
<template><section class="discovery-hero"><aside class="category-panel"><p class="eyebrow">探索你的兴趣</p><h2>课程分类</h2><button class="category-button" :class="{chosen:!category}" @click="filterCategory('')">全部课程 <span>→</span></button><button v-for="item in categories" :key="item.id" class="category-button" :class="{chosen:category===String(item.id)}" @click="filterCategory(String(item.id))">{{item.name}}<span>→</span><small>{{(item.children||[]).slice(0,3).map((c:Row)=>c.name).join(' · ')}}</small></button><p v-if="categoryError" class="muted">{{categoryError}}</p><RouterLink to="/favorites" class="category-bottom">看看收藏的好课 →</RouterLink></aside>
<div class="hero-banner"><div class="hero-copy"><p class="eyebrow">天机学堂 · 在线学习</p><h1>从兴趣出发，<br/>向更好的自己前进。</h1><p>选一门好课，按自己的节奏学习。<br/>用笔记留住思考，用考试检验收获。</p><RouterLink class="hero-cta" to="/learning">进入我的学习 <span>→</span></RouterLink></div><div class="learning-illustration" aria-hidden="true"><div class="illustration-orbit"></div><div class="illustration-window"><i></i><i></i><i></i><span class="code-line">Learn. Practice. Grow.</span><div class="code-bar"></div><div class="code-bar short"></div><div class="illustration-play">▶</div><span class="illustration-caption">每一步，都算数</span></div><div class="floating-note"><span>✓</span> 记录学习的每一次进步</div></div></div></section>
<section class="card catalog-content"><div class="section-heading"><div><p class="eyebrow">发现值得学习的内容</p><h2>课程中心</h2></div><span class="muted">共 {{total}} 门课程</span></div><div class="catalog-search"><el-input v-model="keyword" placeholder="搜索课程" aria-label="搜索课程" clearable @keyup.enter="page=1;load()"/><el-select v-model="sort" aria-label="课程排序" placeholder="排序" style="width:150px" @change="page=1;load()"><el-option label="综合排序" value=""/><el-option label="价格由低到高" value="price"/><el-option label="学习人数" value="sold"/><el-option label="上架时间" value="publishTime"/></el-select><el-button type="primary" @click="page=1;load()">搜索</el-button></div>
<div class="course-filters"><button :class="{chosen:free===''}" @click="free='';page=1;load()">全部课程</button><button :class="{chosen:free==='true'}" @click="free='true';page=1;load()">免费课程</button><button :class="{chosen:free==='false'}" @click="free='false';page=1;load()">付费课程</button><el-button v-if="keyword || category || free" text @click="reset">清除筛选</el-button></div><Status :busy="task.busy.value" :error="task.error.value"/>
<div class="grid course-grid"><article v-for="(course,i) in rows" :key="course.id" class="course-tile"><RouterLink :to="'/courses/'+course.id" class="cover-link" :aria-label="'查看课程：'+course.name"><img v-if="course.coverUrl && !failedCovers.has(course.id)" :src="course.coverUrl" class="course-cover" loading="lazy" :alt="course.name" @error="failedCovers.add(course.id)"/><div v-else class="course-cover designed-cover" :class="'cover-tone-'+i%4"><small>天机学堂 · 精选课程</small><strong>{{course.name}}</strong><span>LEARN · PRACTICE</span></div></RouterLink><div class="course-tile-body"><h3><RouterLink :to="'/courses/'+course.id">{{course.name}}</RouterLink></h3><p class="muted">讲师：{{course.teacher||'课程团队'}}</p><p class="course-meta">{{course.sections ?? 0}} 小节 <span>{{course.sold||0}} 人学习</span></p><div class="tile-bottom"><strong class="price">{{Number(course.price)===0?'免费':money(course.price)}}</strong><RouterLink :to="'/courses/'+course.id">查看课程 →</RouterLink></div></div></article></div><el-empty v-if="!task.busy.value && !rows.length && !task.error.value" description="没有找到课程"><el-button @click="reset">查看全部课程</el-button></el-empty><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="prev,pager,next" @current-change="load"/></section>
</template>
