<script setup lang="ts">
import {ref,onMounted} from 'vue';import {get} from '../../../../packages/shared/src/client';import {useTask,money,query} from '../../../../packages/shared/src/ui';import type {components} from '../../../../packages/shared/src/generated/search';import Status from '../../../../packages/shared/src/Status.vue';
type Course=components['schemas']['CourseVO'];type CoursePage=components['schemas']['PageDTOCourseVO'];
const failedCovers=ref(new Set<string>());
const task=useTask(),keyword=ref(''),page=ref(1),rows=ref<Course[]>([]),total=ref(0),sort=ref('');
async function load(){await task.run(async()=>{const result=await get<CoursePage>('/services/search/courses/portal?'+query({keyword:keyword.value,pageNo:page.value,pageSize:20,sortBy:sort.value}));rows.value=result.list||[];total.value=Number(result.total||0);});}
onMounted(load);
</script>
<template><section class="card"><h2>课程中心</h2><div class="toolbar"><el-input v-model="keyword" placeholder="搜索课程" @keyup.enter="page=1;load()"/><el-select v-model="sort" placeholder="排序" style="width:150px"><el-option label="默认" value=""/><el-option label="价格" value="price"/><el-option label="销量" value="sold"/><el-option label="上架时间" value="publishTime"/></el-select><el-button type="primary" @click="page=1;load()">搜索</el-button></div><Status :busy="task.busy.value" :error="task.error.value"/>
<div class="grid"><article v-for="course in rows" :key="course.id" class="card"><img v-if="course.coverUrl && !failedCovers.has(course.id)" :src="course.coverUrl" class="course-cover" loading="lazy" :alt="course.name" @error="failedCovers.add(course.id)"/><div v-else class="course-cover cover-placeholder" aria-label="暂无课程封面">天机学堂</div><h3><RouterLink :to="'/courses/'+course.id">{{course.name}}</RouterLink></h3><p class="price">{{Number(course.price)===0?'免费':money(course.price)}}</p><p class="muted">{{course.sections ?? 0}} 小节 · {{course.sold||0}} 人学习</p></article></div><el-empty v-if="!task.busy.value && !rows.length && !task.error.value" description="没有找到课程"/><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="prev,pager,next" @current-change="load"/></section></template>