<script setup lang="ts">
import {ref,onMounted,watch} from 'vue';import {get,write} from '../../../../packages/shared/src/client';import {useOperations} from '../../../../packages/shared/src/operations';import {useTask,money,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const statusName=(value:unknown)=>({1:'待支付',2:'已支付',3:'已取消',4:'已完成',5:'免费报名',6:'退款处理中',7:'已退款'}[Number(value)]||'未知状态');
const props=defineProps<{mode:string}>(),task=useTask(),ops=useOperations(),rows=ref<Row[]>([]),selected=ref<Row[]>([]),confirmation=ref<Row>(),discount=ref<number>(-1),exchange=ref(''),detail=ref<Row>(),pay=ref<string>(),page=ref(1),total=ref(0);
async function load(){confirmation.value=undefined;detail.value=undefined;pay.value=undefined;await task.run(async()=>{
 const path=props.mode==='cart'?'/services/trade/carts':props.mode==='coupons'?'/services/promotion/coupons/list':'/orders?pageNo='+page.value+'&pageSize=20';
 const result=await get<Row[]|Row>(path);rows.value=Array.isArray(result)?result:result.list||[];total.value=Array.isArray(result)?result.length:Number(result.total||0);
});}
async function checkout(){await task.run(async()=>{if(!selected.value.length)throw new Error('请选择课程');confirmation.value=await get<Row>('/orders/confirmation?courseIds='+selected.value.map(x=>x.courseId).join(','));discount.value=-1;});}
async function place(){await task.run(async()=>{if(!confirmation.value)return;const result=await ops.begin('trade','创建课程订单','/orders',{orderId:confirmation.value.orderId,courseIds:selected.value.map(x=>x.courseId),couponIds:discount.value<0?[]:confirmation.value.discounts[discount.value].ids});if(result.status==='SUCCEEDED'){confirmation.value=undefined;task.message.value='订单已创建，请到订单页面支付。';}});}
async function claim(id:string){await task.run(async()=>{const result=await ops.begin('promotion','领取优惠券','/coupons/'+id+'/claims',undefined);task.message.value=result.status==='SUCCEEDED'?'领取成功':'正在处理，可在操作记录中继续查询';});}
async function redeem(){await task.run(async()=>{if(!exchange.value.trim())throw new Error('请输入兑换码');const result=await ops.begin('promotion','兑换优惠券','/coupon-exchanges',{code:exchange.value.trim()});task.message.value=result.status==='SUCCEEDED'?'兑换成功':'兑换处理中';});}
async function cancel(id:string){const canceled=await task.run(async()=>{await write('/orders/'+id+'/cancel','PUT');return true;});if(canceled){await load();task.message.value='订单已取消';}}
async function payment(id:string){await task.run(async()=>{const channels=await get<Row[]>('/services/trade/pay/channels');if(!channels.length)throw new Error('支付渠道未配置');pay.value=await write<string>('/services/trade/pay/order','POST',{orderId:id,payChannelCode:channels[0]!.channelCode});});}
watch(()=>props.mode,()=>{page.value=1;void load();});onMounted(load);
</script>
<template><section class="card"><h2>{{mode==='cart'?'购物车':mode==='coupons'?'优惠券':'我的订单'}}</h2><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<div v-if="mode==='coupons'" class="toolbar"><el-input v-model="exchange" placeholder="输入兑换码"/><el-button @click="redeem" :disabled="task.busy.value">兑换</el-button><el-button @click="task.run(async()=>{const r=await get<Row>('/services/promotion/user-coupons/page?pageNo=1&pageSize=100');rows=r.list||[];})">我的券</el-button><el-button @click="load">可领取的券</el-button></div>
<el-table :data="rows" @selection-change="selected=$event"><el-table-column v-if="mode==='cart'" type="selection" :selectable="(row:Row)=>!row.expired"/><el-table-column :label="mode==='coupons'?'优惠券':'名称'"><template #default="{row}">{{row.name??row.courseName??row.details?.map((d:Row)=>d.name).join('、')}}</template></el-table-column><el-table-column v-if="mode==='orders'" prop="id" label="订单号"/><el-table-column v-if="mode==='orders'" label="状态"><template #default="{row}">{{statusName(row.status)}}</template></el-table-column><el-table-column label="金额"><template #default="{row}">{{money(row.realAmount??row.price??row.discountValue)}}</template></el-table-column><el-table-column label="操作"><template #default="{row}">
<el-button v-if="mode==='cart'" @click="task.run(async()=>{await write('/services/trade/carts/'+row.id,'DELETE');rows=rows.filter(x=>x.id!==row.id);})">移除</el-button>
<el-button v-if="mode==='coupons'" @click="claim(row.id)" :disabled="task.busy.value || !!row.termEndTime">领取</el-button>
<template v-if="mode==='orders'"><el-button @click="task.run(async()=>{detail=await get<Row>('/orders/'+row.id);})">详情</el-button><el-button v-if="Number(row.status)===1" @click="payment(row.id)">支付</el-button><el-button v-if="Number(row.status)===1" @click="cancel(row.id)">取消</el-button></template></template></el-table-column></el-table>
<el-button v-if="mode==='cart'" type="primary" :disabled="!selected.length || task.busy.value" @click="checkout">确认选购 {{selected.length}} 门课程</el-button>
<el-pagination v-if="mode==='orders'" v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next" @current-change="load"/>
<article v-if="confirmation" class="card"><h3>确认订单</h3><p>总额 {{money(confirmation.totalAmount)}}</p><el-radio-group v-model="discount"><el-radio :value="-1">不使用优惠券</el-radio><el-radio v-for="(d,i) in confirmation.discounts" :key="i" :value="i">减 {{money(d.discountAmount)}} · {{(d.rules||[]).join('、')}}</el-radio></el-radio-group><p>订单 {{confirmation.orderId}}</p><el-button type="primary" @click="place" :disabled="task.busy.value">提交订单</el-button></article>
<article v-if="detail" class="card"><h3>订单 {{detail.id}}</h3><p>状态 {{statusName(detail.status)}} · 实付 {{money(detail.realAmount)}}</p><div v-for="item in detail.details||detail.orderDetails" :key="item.id" class="section">{{item.name}} · {{money(item.realPayAmount)}}<el-button v-if="item.canRefund===true" @click="task.run(async()=>{await ops.begin('trade','提交退款申请','/services/trade/refund-apply',{orderDetailId:item.id,refundReason:'用户申请退款',questionDesc:'用户申请退款'});task.message.value='退款申请已提交';})">申请退款</el-button></div></article>
<article v-if="pay" class="card"><h3>支付请求</h3><el-alert title="仅支付成功通知落库后，订单才会更新为已支付。未配置支付渠道时不会自动成功。" type="info" :closable="false"/><RouterLink v-if="pay.startsWith('/simulate-payment/')" :to="pay">打开本地模拟支付</RouterLink><a v-else :href="pay" target="_blank" rel="noopener">打开支付渠道</a><el-button @click="load">刷新订单状态</el-button></article>
</section></template>
