<script setup lang="ts">
import {ref,onMounted,watch} from 'vue';import {useRoute,useRouter} from 'vue-router';import {get,write} from '../../../../packages/shared/src/client';import {useOperations} from '../../../../packages/shared/src/operations';import {useTask,money,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const statusName=(value:unknown)=>({1:'待支付',2:'已支付',3:'已取消',4:'已完成',5:'免费报名',6:'退款处理中',7:'已退款'}[Number(value)]||'未知状态');
const props=defineProps<{mode:string}>(),route=useRoute(),router=useRouter(),task=useTask(),ops=useOperations(),rows=ref<Row[]>([]),selected=ref<Row[]>([]),confirmation=ref<Row>(),discount=ref(-1),exchange=ref(''),detail=ref<Row>(),pay=ref(''),page=ref(1),total=ref(0),checkoutOpen=ref(false),checkoutPay=ref(false),detailOpen=ref(false),paymentOpen=ref(false),created=ref(''),cancelId=ref(''),refund=ref<Row>(),refundReason=ref(''),myCoupons=ref(false),channels=ref<Row[]>([]),channel=ref(''),paymentOrder=ref('');
async function load(){await task.run(async()=>{
 const path=props.mode==='cart'?'/services/trade/carts':props.mode==='coupons'?(myCoupons.value?'/services/promotion/user-coupons/page?pageNo=1&pageSize=100':'/services/promotion/coupons/list'):'/orders?pageNo='+page.value+'&pageSize=20';
 const result=await get<Row[]|Row>(path);rows.value=Array.isArray(result)?result:result.list||[];total.value=Array.isArray(result)?result.length:Number(result.total||0);
});if(props.mode==='orders' && typeof route.query.pay==='string'){const id=route.query.pay;await router.replace('/orders');await payment(id);}}
async function checkout(){await task.run(async()=>{if(!selected.value.length)throw new Error('请选择课程');confirmation.value=await get<Row>('/orders/confirmation?courseIds='+selected.value.map(x=>x.courseId).join(','));discount.value=-1;created.value='';checkoutOpen.value=true;});}
async function place(){await task.run(async()=>{if(!confirmation.value)return;const id=String(confirmation.value.orderId),result=await ops.begin('trade','创建课程订单','/orders',{orderId:id,courseIds:selected.value.map(x=>x.courseId),couponIds:discount.value<0?[]:confirmation.value.discounts[discount.value].ids});if(result.status==='SUCCEEDED'){created.value=id;task.message.value='订单已创建，可以继续付款';rows.value=rows.value.filter(x=>!selected.value.some(s=>s.id===x.id));selected.value=[];}else task.message.value='订单正在创建，请在操作记录中查看结果后继续付款';});}
function payCreated(){checkoutPay.value=true;checkoutOpen.value=false;}
function checkoutClosed(){if(checkoutPay.value){checkoutPay.value=false;void router.push('/orders?pay='+created.value);}}
async function claim(id:string){await task.run(async()=>{const result=await ops.begin('promotion','领取优惠券','/coupons/'+id+'/claims',undefined);task.message.value=result.status==='SUCCEEDED'?'领取成功，可在我的优惠券中查看':'正在处理，可在操作记录中继续查询';});}
async function redeem(){await task.run(async()=>{if(!exchange.value.trim())throw new Error('请输入兑换码');const result=await ops.begin('promotion','兑换优惠券','/coupon-exchanges',{code:exchange.value.trim()});task.message.value=result.status==='SUCCEEDED'?'兑换成功，可在我的优惠券中查看':'兑换处理中';});}
async function cancel(){const done=await task.run(async()=>{await write('/orders/'+cancelId.value+'/cancel','PUT');cancelId.value='';return true;});if(done){await load();task.message.value='订单已取消';}}
async function showDetail(id:string){await task.run(async()=>{detail.value=await get<Row>('/orders/'+id);detailOpen.value=true;});}
async function payment(id:string){pay.value='';paymentOrder.value=id;paymentOpen.value=true;await task.run(async()=>{channels.value=await get<Row[]>('/services/trade/pay/channels');if(!channels.value.length)throw new Error('支付服务暂不可用，请稍后重试或联系管理员');channel.value=String(channels.value[0]!.channelCode);if(channels.value.length===1)await createPayment();});}
async function createPayment(){pay.value=await write<string>('/services/trade/pay/order','POST',{orderId:paymentOrder.value,payChannelCode:channel.value});}
async function submitRefund(){const done=await task.run(async()=>{if(!refund.value || !refundReason.value.trim())return false;const result=await ops.begin('trade','提交退款申请','/services/trade/refund-apply',{orderDetailId:refund.value.id,refundReason:refundReason.value.trim(),questionDesc:refundReason.value.trim()});refund.value=undefined;detailOpen.value=false;return result.status==='SUCCEEDED';});if(done){await load();task.message.value='退款申请已提交';}else if(!task.error.value)task.message.value='退款申请正在处理，请在操作记录中查看结果';}
watch(()=>props.mode,()=>{page.value=1;rows.value=[];selected.value=[];checkoutOpen.value=false;detailOpen.value=false;paymentOpen.value=false;void load();});onMounted(load);
</script>
<template><section class="card commerce-page"><div class="section-heading"><div><p class="eyebrow">{{mode==='cart'?'选好课程，开始下一段学习':mode==='coupons'?'让好课更实惠':'每一次学习，都有记录'}}</p><h2>{{mode==='cart'?'购物车':mode==='coupons'?'优惠券':'我的订单'}}</h2></div><RouterLink to="/">继续选课 →</RouterLink></div><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<div v-if="mode==='coupons'" class="toolbar"><el-button :type="!myCoupons?'primary':'default'" @click="myCoupons=false;load()">可领取的券</el-button><el-button :type="myCoupons?'primary':'default'" @click="myCoupons=true;load()">我的优惠券</el-button><el-input v-model="exchange" placeholder="输入兑换码" aria-label="兑换码"/><el-button @click="redeem" :disabled="task.busy.value || !exchange.trim()">兑换</el-button></div>
<el-table :data="rows" @selection-change="selected=$event" empty-text="暂无记录"><el-table-column v-if="mode==='cart'" type="selection" :selectable="(row:Row)=>!row.expired"/><el-table-column :label="mode==='coupons'?'优惠券':'名称'" min-width="160"><template #default="{row}"><strong>{{row.name??row.courseName??row.details?.map((d:Row)=>d.name).join('、')}}</strong><p v-if="row.expired" class="muted">课程暂不可购买</p></template></el-table-column><el-table-column v-if="mode==='orders'" prop="id" label="订单号" min-width="180"/><el-table-column v-if="mode==='orders'" label="状态" width="110"><template #default="{row}"><el-tag :type="Number(row.status)===1?'warning':[3,7].includes(Number(row.status))?'info':'success'" effect="light">{{statusName(row.status)}}</el-tag></template></el-table-column><el-table-column :label="mode==='coupons'?'优惠':'金额'" width="110"><template #default="{row}">{{mode==='coupons'&&Number(row.discountType)===2?row.discountValue+'% 折扣':money(row.realAmount??row.price??row.discountValue)}}</template></el-table-column><el-table-column label="操作" :min-width="mode==='orders'?220:100"><template #default="{row}">
<el-button v-if="mode==='cart'" text @click="task.run(async()=>{await write('/services/trade/carts/'+row.id,'DELETE');rows=rows.filter(x=>x.id!==row.id);})">移除</el-button>
<el-button v-if="mode==='coupons' && !myCoupons" type="primary" plain @click="claim(row.id)" :disabled="task.busy.value">领取</el-button><span v-else-if="mode==='coupons'">已领取</span>
<template v-if="mode==='orders'"><el-button text @click="showDetail(row.id)">详情</el-button><el-button v-if="Number(row.status)===1" type="primary" @click="payment(row.id)" :disabled="task.busy.value">支付</el-button><el-button v-if="Number(row.status)===1" text @click="cancelId=row.id" :disabled="task.busy.value">取消</el-button></template></template></el-table-column></el-table>
<el-empty v-if="!rows.length && !task.busy.value && !task.error.value" :description="mode==='cart'?'购物车还是空的，去发现一门好课吧':mode==='orders'?'暂时没有订单':'暂时没有优惠券'"><RouterLink class="text-action" to="/">去课程中心看看 →</RouterLink></el-empty>
<div v-if="mode==='cart' && rows.length" class="checkout-bar"><span>已选 <strong>{{selected.length}}</strong> 门课程</span><el-button type="primary" size="large" :disabled="!selected.length || task.busy.value" @click="checkout">确认选购 {{selected.length}} 门课程</el-button></div>
<el-pagination v-if="mode==='orders'" v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next" @current-change="load"/>
<el-dialog v-model="checkoutOpen" @closed="checkoutClosed" destroy-on-close :title="created?'订单创建成功':'确认订单'" class="purchase-dialog" :close-on-click-modal="!task.busy.value"><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/><template v-if="confirmation && !created"><div v-for="item in selected" :key="item.id" class="order-line"><strong>{{item.courseName}}</strong><span>{{money(item.price)}}</span></div><h3>课程总额 {{money(confirmation.totalAmount)}}</h3><p class="muted">选择优惠方案</p><el-radio-group v-model="discount" class="discount-options"><el-radio :value="-1">不使用优惠券</el-radio><el-radio v-for="(d,i) in confirmation.discounts" :key="i" :value="i">减 {{money(d.discountAmount)}} · {{(d.rules||[]).join('、')}}</el-radio></el-radio-group><div class="checkout-total"><span>应付金额</span><strong class="price">{{money(Number(confirmation.totalAmount)-(discount<0?0:Number(confirmation.discounts[discount]?.discountAmount||0)))}}</strong></div></template><template v-else-if="created"><p>订单已创建，请完成付款。付款结果确认后，课程会出现在「我的学习」。</p><p class="muted">订单号 {{created}}</p></template><template #footer><el-button @click="checkoutOpen=false" :disabled="task.busy.value">{{created?'稍后付款':'返回修改'}}</el-button><el-button v-if="created" type="primary" @click="payCreated">立即付款</el-button><el-button v-else type="primary" @click="place" :disabled="task.busy.value">提交订单</el-button></template></el-dialog>
<el-dialog v-model="detailOpen" title="订单详情" class="purchase-dialog"><template v-if="detail"><p class="muted">订单号 {{detail.id}}</p><p><el-tag>{{statusName(detail.status)}}</el-tag> · 实付 {{money(detail.realAmount)}}</p><div v-for="item in detail.details||detail.orderDetails" :key="item.id" class="order-line"><div><strong>{{item.name}}</strong><p>{{money(item.realPayAmount)}}</p></div><el-button v-if="item.canRefund===true" @click="refund=item;refundReason=''">申请退款</el-button><RouterLink :to="'/courses/'+item.courseId">查看课程 →</RouterLink></div></template></el-dialog>
<el-dialog v-model="paymentOpen" title="完成付款" class="purchase-dialog"><Status :busy="task.busy.value" :error="task.error.value"/><p class="muted">订单号 {{paymentOrder}}</p><template v-if="channels.length>1"><el-select v-model="channel" aria-label="支付方式" @change="pay=''"><el-option v-for="item in channels" :key="item.channelCode" :label="item.channelName||item.channelCode" :value="String(item.channelCode)"/></el-select><el-button @click="task.run(createPayment)" :disabled="task.busy.value">使用此方式付款</el-button></template><p>付款后可刷新订单查看结果。若暂时没有更新，请稍后再试。</p><RouterLink v-if="pay.startsWith('/simulate-payment/')" class="payment-link" :to="pay">打开本地模拟支付 →</RouterLink><a v-else-if="pay" class="payment-link" :href="pay" target="_blank" rel="noopener">打开支付渠道 →</a><template #footer><el-button @click="paymentOpen=false">稍后付款</el-button><el-button type="primary" @click="paymentOpen=false;load()">刷新订单状态</el-button></template></el-dialog>
<el-dialog :model-value="!!cancelId" title="取消这笔订单？" class="purchase-dialog" @update:model-value="(open:boolean)=>{if(!open)cancelId='';}"><Status :error="task.error.value"/><p>取消后可以重新下单，已预占的优惠券将释放。</p><template #footer><el-button @click="cancelId=''">继续保留</el-button><el-button type="danger" @click="cancel" :disabled="task.busy.value">确认取消订单</el-button></template></el-dialog>
<el-dialog :model-value="!!refund" title="申请课程退款" class="purchase-dialog" @update:model-value="(open:boolean)=>{if(!open)refund=undefined;}"><Status :error="task.error.value"/><p>{{refund?.name}} · {{money(refund?.realPayAmount)}}</p><el-alert title="退款需要审核。退款完成后无法继续观看该课程，已有学习记录和笔记会保留。" type="info" :closable="false"/><el-input v-model="refundReason" type="textarea" :rows="4" placeholder="请说明退款原因" maxlength="500"/><template #footer><el-button @click="refund=undefined">暂不退款</el-button><el-button type="primary" @click="submitRefund" :disabled="!refundReason.trim() || task.busy.value">提交退款申请</el-button></template></el-dialog>
</section></template>
