<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount,watch} from 'vue';import {useRoute} from 'vue-router';import {get,write} from '../../../../packages/shared/src/client';import {useOperations} from '../../../../packages/shared/src/operations';import {useTask,money,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const route=useRoute(),task=useTask(),ops=useOperations(),course=ref<Row>(),lesson=ref<Row>(),section=ref<Row>(),play=ref<Row>(),favorite=ref(false),note=ref(''),questions=ref<Row[]>([]),replies=ref<Row[]>([]),question=ref<Row>(),title=ref(''),description=ref(''),reply=ref(''),video=ref<HTMLVideoElement>(),moment=ref(0);let lastSaved=0;
const id=()=>String(route.params.id);
async function load(){await task.run(async()=>{course.value=await get<Row>('/services/course/course/'+id()+'?withCatalogue=true&withTeachers=true');favorite.value=(await get<{favorited:boolean}>('/favorites/'+id())).favorited;lesson.value=await get<Row>('/services/learning/learning-records/course/'+id());});}
async function select(item:Row){section.value=item;play.value=undefined;moment.value=0;lastSaved=0;if(Number(item.type)!==2)return;await task.run(async()=>{play.value=await get<Row>('/services/media/medias/signature/play?sectionId='+item.id);});}
async function record(){if(!lesson.value?.id || !section.value || !video.value)return;const now=Math.floor(video.value.currentTime);if(now-lastSaved<15 && !video.value.ended)return;await task.run(async()=>{await write('/services/learning/learning-records','POST',{lessonId:lesson.value!.id,sectionId:section.value!.id,sectionType:1,moment:now});lastSaved=now;});}
async function saveNote(){await task.run(async()=>{const op=await ops.begin('learning','保存私人笔记','/notes',{courseId:id(),sectionId:section.value?.id,moment:section.value?moment.value:undefined,content:note.value});if(op.status==='SUCCEEDED'){note.value='';task.message.value='笔记已保存';}});}
async function loadQuestions(){await task.run(async()=>{const result=await get<Row>('/services/learning/questions/page?courseId='+id()+'&pageNo=1&pageSize=20');questions.value=result.list||[];});}
async function ask(){const saved=await task.run(async()=>{if(!section.value)throw new Error('请先选择小节');const chapter=course.value?.chapters?.find((c:Row)=>c.sections?.some((s:Row)=>s.id===section.value!.id));const result=await ops.begin('learning','课程提问','/services/learning/questions',{courseId:id(),chapterId:chapter?.id,sectionId:section.value.id,title:title.value,description:description.value,anonymity:false});if(result.status!=='SUCCEEDED'){task.message.value='提问处理中，可在操作记录中继续查询';return false;}title.value='';description.value='';return true;});if(saved)await loadQuestions();}
async function answers(item:Row){question.value=item;await task.run(async()=>{const r=await get<Row>('/services/learning/replies/page?questionId='+item.id+'&pageNo=1&pageSize=100');replies.value=r.list||[];});}
async function respond(){const saved=await task.run(async()=>{if(!question.value)return;const result=await ops.begin('learning','回答课程问题','/services/learning/replies',{questionId:question.value.id,content:reply.value,anonymity:false});if(result.status!=='SUCCEEDED'){task.message.value='回答处理中，可在操作记录中继续查询';return false;}reply.value='';return true;});if(saved && question.value)await answers(question.value);}
watch(()=>route.params.id,()=>{course.value=undefined;lesson.value=undefined;section.value=undefined;void load();});onMounted(load);onBeforeUnmount(()=>{void record();});
</script>
<template><section class="card"><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/><template v-if="course"><h2>{{course.name}}</h2><p class="price">{{money(course.price)}}</p><div class="toolbar"><el-button :disabled="task.busy.value" v-if="!course.free" @click="task.run(async()=>{await write('/services/trade/carts','POST',{courseId:id()});task.message.value='已加入购物车';})">加入购物车</el-button><el-button :disabled="task.busy.value" v-if="course.free" @click="task.run(async()=>{const result=await ops.begin('trade','免费课报名','/orders/free-courses/'+id(),{});if(result.status==='SUCCEEDED')await load();else task.message.value='报名处理中，可在操作记录中继续查询';})">免费报名</el-button><el-button :disabled="task.busy.value" @click="task.run(async()=>{await write('/favorites/'+id(),favorite?'DELETE':'PUT');favorite=!favorite;})">{{favorite?'取消收藏':'收藏课程'}}</el-button><RouterLink :to="'/exams?courseId='+id()">参加考试</RouterLink></div>
<div v-for="chapter in course.chapters" :key="chapter.id"><h3>{{chapter.name}}</h3><div v-for="item in chapter.sections" :key="item.id" class="section"><el-button :disabled="task.busy.value" link @click="select(item)">{{item.index}}. {{item.name}}</el-button><small> {{Number(item.type)===3?'考试':item.mediaDuration+' 秒'}}</small></div></div>
<article v-if="section" class="card"><h3>{{section.name}}</h3><RouterLink v-if="Number(section.type)===3" :to="'/exams?courseId='+id()">前往考试</RouterLink><template v-else><video v-if="play?.playUrl" ref="video" :src="play.playUrl" controls style="width:100%" @timeupdate="moment=Math.floor(video!.currentTime);record()" @ended="record"/><el-alert v-else-if="play" title="播放渠道已返回授权信息，但当前未配置对应播放器。请联系管理员配置视频渠道。" type="warning" :closable="false"/><p v-if="lesson?.id">观看进度会自动保存；考试完成由评分结果更新。</p></template>
<el-input v-model="note" type="textarea" :rows="4" maxlength="10000" placeholder="记录私人笔记"/><p class="muted">小节 {{section.name}} · 时间点 {{moment}} 秒</p><el-button @click="saveNote" :disabled="!note.trim() || task.busy.value">保存笔记</el-button></article>
<article class="card"><h3>课程互动</h3><el-button @click="loadQuestions">查看讨论</el-button><div v-for="item in questions" :key="item.id" class="section"><el-button link @click="answers(item)">{{item.title}}</el-button><p>{{item.description}}</p></div><el-input v-model="title" placeholder="问题标题"/><el-input v-model="description" type="textarea" placeholder="描述问题"/><el-button @click="ask" :disabled="!title || !description || !section || task.busy.value">在当前小节提问</el-button>
<div v-if="question"><h4>{{question.title}}</h4><article v-for="item in replies" :key="item.id" class="section"><p class="content">{{item.content}}</p><el-button @click="task.run(async()=>{await write('/services/remark/likes','POST',{bizId:item.id,bizType:'QA',liked:true});})">赞 {{item.likedTimes||0}}</el-button></article><el-input v-model="reply" type="textarea" placeholder="写下回答"/><el-button @click="respond" :disabled="!reply || task.busy.value">提交回答</el-button></div></article>
</template></section></template>
