<script setup lang="ts">
import {ref,computed,onMounted,onBeforeUnmount,watch} from 'vue';import {useRoute} from 'vue-router';import {get,write} from '../../../../packages/shared/src/client';import {useOperations} from '../../../../packages/shared/src/operations';import {useTask,money,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const route=useRoute(),task=useTask(),ops=useOperations(),course=ref<Row>(),lesson=ref<Row>(),section=ref<Row>(),play=ref<Row>(),favorite=ref(false),added=ref(false),coverFailed=ref(false),note=ref(''),questions=ref<Row[]>([]),replies=ref<Row[]>([]),question=ref<Row>(),title=ref(''),description=ref(''),reply=ref(''),video=ref<HTMLVideoElement>(),moment=ref(0),tab=ref('catalogue'),discussionLoaded=ref(false);let lastSaved=0;
const id=()=>String(route.params.id),sections=computed<Row[]>(()=>course.value?.chapters?.flatMap((c:Row)=>c.sections||[])||[]);
const owned=computed(()=>!!lesson.value?.id && Number(lesson.value.status)!==3 && (!lesson.value.expireTime || new Date(lesson.value.expireTime).getTime()>Date.now()));
const enrollmentEnded=computed(()=>!!course.value?.purchaseEndTime && new Date(course.value.purchaseEndTime).getTime()<Date.now());
const completed=(item:Row)=>lesson.value?.records?.some((r:Row)=>String(r.sectionId)===String(item.id)&&r.finished);
const totalSections=computed(()=>Number(course.value?.sectionNum)||sections.value.length);
const progress=computed(()=>totalSections.value?Math.min(100,Math.round(Number(lesson.value?.learnedSections??sections.value.filter(completed).length)/totalSections.value*100)):0);
const plain=(value:unknown)=>String(value||'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ');
async function load(){await task.run(async()=>{course.value=await get<Row>('/services/course/course/'+id()+'?withCatalogue=true&withTeachers=true');favorite.value=(await get<{favorited:boolean}>('/favorites/'+id())).favorited;lesson.value=await get<Row>('/services/learning/learning-records/course/'+id());});}
async function enroll(){const result=await task.run(()=>ops.begin('trade','免费课报名','/orders/free-courses/'+id(),{}));if(result?.status==='SUCCEEDED'){await load();task.message.value=owned.value?'报名成功，选择小节开始学习吧':'报名成功，学习权限准备中，请稍后刷新页面';}else if(result)task.message.value='报名处理中，可在操作记录中继续查询';}
async function addCart(){await task.run(async()=>{await write('/services/trade/carts','POST',{courseId:id()});added.value=true;task.message.value='已加入购物车';});}
async function toggleFavorite(){await task.run(async()=>{await write('/favorites/'+id(),favorite.value?'DELETE':'PUT');favorite.value=!favorite.value;task.message.value=favorite.value?'已收藏，可在我的收藏中查看':'已取消收藏';});}
async function select(item:Row){if(!owned.value && Number(item.type)===2 && !item.trailer){task.message.value=lesson.value?.id?'学习权益已失效，请重新报名后学习':'报名后可学习当前小节';return;}section.value=item;play.value=undefined;const previous=lesson.value?.records?.find((r:Row)=>String(r.sectionId)===String(item.id));moment.value=Number(previous?.moment||0);lastSaved=moment.value;if(Number(item.type)!==2)return;await task.run(async()=>{play.value=await get<Row>('/services/media/medias/signature/play?sectionId='+item.id);});}
function resumeVideo(){if(video.value && Number.isFinite(video.value.duration))video.value.currentTime=Math.min(moment.value,Math.max(0,video.value.duration-0.2));}
async function continueLearning(){tab.value='catalogue';const next=sections.value.find(x=>!completed(x))||sections.value[0];if(next)await select(next);}
async function record(){if(!owned.value || !section.value || !video.value)return;const now=Math.floor(video.value.currentTime),ended=video.value.ended;if(now-lastSaved<15 && !ended)return;await task.run(async()=>{await write('/services/learning/learning-records','POST',{lessonId:lesson.value!.id,sectionId:section.value!.id,sectionType:1,moment:now});lastSaved=now;if(ended)lesson.value=await get<Row>('/services/learning/learning-records/course/'+id());});}
async function saveNote(){await task.run(async()=>{const op=await ops.begin('learning','保存私人笔记','/notes',{courseId:id(),sectionId:section.value?.id,moment:section.value?moment.value:undefined,content:note.value});if(op.status==='SUCCEEDED'){note.value='';task.message.value='笔记已保存';}else task.message.value='笔记保存中，可在操作记录中查询';});}
async function loadQuestions(){await task.run(async()=>{const result=await get<Row>('/services/learning/questions/page?courseId='+id()+'&pageNo=1&pageSize=20');questions.value=result.list||[];discussionLoaded.value=true;});}
async function ask(){const saved=await task.run(async()=>{if(!section.value)throw new Error('请先选择小节');const chapter=course.value?.chapters?.find((c:Row)=>c.sections?.some((s:Row)=>s.id===section.value!.id));const result=await ops.begin('learning','课程提问','/services/learning/questions',{courseId:id(),chapterId:chapter?.id,sectionId:section.value.id,title:title.value,description:description.value,anonymity:false});if(result.status!=='SUCCEEDED'){task.message.value='提问处理中，可在操作记录中继续查询';return false;}title.value='';description.value='';return true;});if(saved)await loadQuestions();}
async function answers(item:Row){question.value=item;await task.run(async()=>{const r=await get<Row>('/services/learning/replies/page?questionId='+item.id+'&pageNo=1&pageSize=100');replies.value=r.list||[];});}
async function respond(){const saved=await task.run(async()=>{if(!question.value)return;const result=await ops.begin('learning','回答课程问题','/services/learning/replies',{questionId:question.value.id,content:reply.value,anonymity:false});if(result.status!=='SUCCEEDED'){task.message.value='回答处理中，可在操作记录中继续查询';return false;}reply.value='';return true;});if(saved && question.value)await answers(question.value);}
async function like(item:Row){await task.run(async()=>{const liked=!item.liked;await write('/services/remark/likes','POST',{bizId:item.id,bizType:'QA',liked});item.liked=liked;item.likedTimes=Math.max(0,Number(item.likedTimes||0)+(liked?1:-1));task.message.value=liked?'已点赞':'已取消点赞';});}
watch(()=>route.params.id,()=>{course.value=undefined;lesson.value=undefined;section.value=undefined;coverFailed.value=false;questions.value=[];replies.value=[];question.value=undefined;added.value=false;tab.value='catalogue';discussionLoaded.value=false;void load();});onMounted(load);onBeforeUnmount(()=>{void record();});
</script>
<template><div class="course-page"><RouterLink to="/" class="breadcrumb">课程中心 / 课程详情</RouterLink><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<template v-if="course"><section class="course-intro card"><img v-if="course.coverUrl && !coverFailed" :src="course.coverUrl" :alt="course.name" class="course-intro-art actual-course-cover" @error="coverFailed=true"/><div v-else class="course-intro-art designed-cover"><small>天机学堂 · 在线课程</small><strong>{{course.name}}</strong><span>LEARN AT YOUR OWN PACE</span></div><div class="course-intro-copy"><p class="eyebrow">发现 · 学习 · 实践</p><h1>{{course.name}}</h1><p class="muted">{{totalSections}} 小节 · {{(course.teachers||[]).map((t:Row)=>t.name).filter(Boolean).join('、')||'天机学堂课程团队'}}</p><p v-if="course.introduce" class="content">{{plain(course.introduce)}}</p><p class="price">{{Number(course.price)===0?'免费课程':money(course.price)}}</p><div class="toolbar"><template v-if="!owned && enrollmentEnded"><el-button size="large" disabled>报名已结束</el-button><span class="muted">已超过报名截止时间</span></template><template v-else-if="!owned"><el-button v-if="Number(course.price)!==0" type="primary" size="large" :disabled="task.busy.value" @click="addCart">加入购物车</el-button><el-button v-else type="primary" size="large" :disabled="task.busy.value" @click="enroll">免费报名</el-button><RouterLink v-if="added" to="/cart" class="text-action">去购物车结算 →</RouterLink></template><el-button v-else type="primary" size="large" @click="continueLearning" :disabled="task.busy.value">继续学习</el-button><el-button :disabled="task.busy.value" @click="toggleFavorite">{{favorite?'取消收藏':'收藏课程'}}</el-button><RouterLink v-if="owned" :to="'/exams?courseId='+id()">参加考试 →</RouterLink><RouterLink v-else-if="lesson?.id" :to="'/exams?courseId='+id()">查看考试记录 →</RouterLink><span v-else class="muted">报名后可参加考试</span></div><div v-if="owned" class="learning-progress"><span>课程学习进度</span><el-progress :percentage="progress"/></div></div></section>
<el-alert v-if="!task.busy.value && lesson?.id && !owned" class="enrollment-hint" title="学习权益已失效" description="学习进度、私人笔记和已有答卷仍保留。重新报名后可继续学习。" type="warning" :closable="false" show-icon/>
<el-tabs v-model="tab" class="course-tabs"><el-tab-pane label="课程目录" name="catalogue"/><el-tab-pane label="课程介绍" name="intro"/><el-tab-pane label="课程互动" name="discussion"/></el-tabs>
<section v-if="tab==='intro'" class="card"><h2>关于这门课程</h2><p class="content">{{plain(course.detail||course.introduce)||'课程介绍暂未完善，可以先查看课程目录了解学习内容。'}}</p><h3 v-if="course.usePeople">适用人群</h3><p>{{course.usePeople}}</p></section>
<div v-show="tab==='catalogue'" class="course-study-layout"><aside class="card syllabus"><h2>课程目录</h2><div v-for="chapter in course.chapters" :key="chapter.id"><h3>{{chapter.name}}</h3><button v-for="item in chapter.sections" :key="item.id" class="lesson-item" :class="{current:section?.id===item.id}" :disabled="task.busy.value || (!owned && Number(item.type)===2 && !item.trailer)" @click="select(item)"><span class="lesson-type">{{Number(item.type)===3?'测':'▶'}}</span><span>{{item.index}}. {{item.name}}<small>{{Number(item.type)===3?'考试':Math.ceil(Number(item.mediaDuration||0)/60)+' 分钟'}}<template v-if="!owned && Number(item.type)===2"> · {{item.trailer?'可试看':'报名后学习'}}</template></small></span><span v-if="completed(item)" class="lesson-done">已完成</span></button></div><el-empty v-if="!sections.length" description="课程目录正在完善"/></aside>
<article class="card lesson-workspace"><template v-if="section"><h2>{{section.name}}</h2><RouterLink v-if="Number(section.type)===3 && owned" class="text-action" :to="'/exams?courseId='+id()">前往考试 →</RouterLink><RouterLink v-else-if="Number(section.type)===3 && lesson?.id" class="text-action" :to="'/exams?courseId='+id()">查看考试记录 →</RouterLink><p v-else-if="Number(section.type)===3" class="muted">报名后可参加考试</p><template v-else><video v-if="play?.playUrl" ref="video" :src="play.playUrl" controls class="course-player" @loadedmetadata="resumeVideo" @timeupdate="moment=Math.floor(video!.currentTime);record()" @ended="record"/><el-alert v-else-if="play" title="当前视频播放渠道暂不可用，请联系管理员。" type="warning" :closable="false"/><p v-if="owned" class="muted">学习进度自动保存，下次可继续观看。</p></template><div class="note-composer"><div class="section-heading"><h3>随堂笔记</h3><RouterLink to="/notes">全部笔记 →</RouterLink></div><el-input v-model="note" type="textarea" :rows="4" maxlength="10000" placeholder="记录私人笔记"/><div class="toolbar"><small>仅自己可见 · {{moment}} 秒</small><el-button type="primary" @click="saveNote" :disabled="!note.trim() || task.busy.value || !owned">保存笔记</el-button></div></div></template><div v-else class="workspace-empty"><div class="workspace-play">▶</div><h3>{{owned?'准备好开始学习了吗？':'先了解这门课程'}}</h3><p class="muted">{{owned?'选择左侧小节，继续你的学习。':'查看目录，报名后即可开始学习和记录笔记。'}}</p><el-button v-if="owned" type="primary" @click="continueLearning">开始学习</el-button></div></article></div>
<article v-show="tab==='discussion' || section" class="card discussion"><div class="section-heading"><div><h2>课程互动</h2><p class="muted">遇到问题？和同学一起交流思路。</p></div><el-button @click="loadQuestions" :disabled="task.busy.value">查看讨论</el-button></div><el-empty v-if="discussionLoaded && !questions.length" description="还没有讨论，来提出第一个问题吧"/><div v-for="item in questions" :key="item.id" class="section"><el-button link @click="answers(item)">{{item.title}}</el-button><p>{{item.description}}</p></div><div class="question-composer"><p v-if="!section" class="muted">先在课程目录选择一个小节，再发起提问。</p><el-input v-model="title" placeholder="问题标题" maxlength="200"/><el-input v-model="description" type="textarea" placeholder="描述问题" :rows="3"/><el-button type="primary" @click="ask" :disabled="!title.trim() || !description.trim() || !section || task.busy.value || !owned">在当前小节提问</el-button></div>
<div v-if="question"><h3>{{question.title}}</h3><article v-for="item in replies" :key="item.id" class="section"><p class="content">{{item.content}}</p><el-button :type="item.liked?'primary':'default'" :aria-pressed="!!item.liked" :disabled="task.busy.value" @click="like(item)">{{item.liked?'已赞':'赞'}} {{item.likedTimes||0}}</el-button></article><el-input v-model="reply" type="textarea" placeholder="写下回答"/><el-button @click="respond" :disabled="!reply.trim() || task.busy.value || !owned">提交回答</el-button></div></article></template></div></template>
