<script setup lang="ts">
import {ref,computed,onMounted,watch} from 'vue';import {ElMessageBox} from 'element-plus';import {useExamDraft} from '../composables/examDraft';import {useRoute} from 'vue-router';import {ApiError,get} from '../../../../packages/shared/src/client';import {useOperations} from '../../../../packages/shared/src/operations';import {useTask,examStatus,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const route=useRoute(),courseId=ref(String(route.query.courseId||'')),course=ref<Row>(),lessons=ref<Row[]>([]),lessonPage=ref(0),lessonTotal=ref(0),papers=ref<Row[]>([]),attempt=ref<Row>(),responses=ref<Record<string,string>>({}),backupOpen=ref(false),submitOpen=ref(false),task=useTask(),ops=useOperations();
const answered=computed(()=>attempt.value?.questions?.filter((q:Row)=>responses.value[q.question_id]?.trim()).length||0);
const sectionName=(id:string)=>course.value?.chapters?.flatMap((c:Row)=>c.sections||[]).find((s:Row)=>String(s.id)===String(id))?.name||'课程测验';
const typeName=(value:unknown)=>({1:'单选题',2:'多选题',3:'不定项选择题',4:'判断题',5:'主观题'}[Number(value)]||'题目');
const savedDraft=useExamDraft(attempt,responses);
const enrollmentHint=ref('');
const activeLesson=(lesson:Row)=>Number(lesson.status)!==3 && (!lesson.expireTime || new Date(lesson.expireTime).getTime()>Date.now());
const selectedLesson=computed(()=>lessons.value.find(lesson=>String(lesson.courseId)===courseId.value));
const lessonLabel=(lesson:Row)=>(lesson.courseName||'已报名课程')+(activeLesson(lesson)?'':'（权益已失效）');
async function showAttempt(value:Row){attempt.value=value;if(value.status==='IN_PROGRESS')await savedDraft.restore(value);else {responses.value=Object.fromEntries((value.answers||[]).map((a:Row)=>[String(a.question_id),a.response||'']));await savedDraft.restore(value);}}
async function loadLatestDraft(){try{await ElMessageBox.confirm('当前未同步答案会另存为本机备份，再载入服务器上的最新草稿。是否继续？','载入最新草稿',{confirmButtonText:'载入最新草稿',cancelButtonText:'保留本机答案'});await task.run(savedDraft.loadLatest);}catch{}}
async function moreCourses(){await task.run(async()=>{const result=await get<Row>('/services/learning/lessons/page?pageNo='+(lessonPage.value+1)+'&pageSize=20');lessons.value.push(...(result.list||[]));lessonTotal.value=Number(result.total||0);lessonPage.value++;});}
async function load(){if(!courseId.value)return;await task.run(async()=>{
 enrollmentHint.value='';papers.value=[];
 if(selectedLesson.value && !activeLesson(selectedLesson.value)){enrollmentHint.value='这门课程的学习权益已失效，暂不能参加考试。学习记录和已有答卷仍然保留，可返回我的学习查看，或联系学校管理员。';return;}
 try{const [list,detail]=await Promise.all([get<Row[]>('/exam-papers?courseId='+encodeURIComponent(courseId.value)),get<Row>('/services/course/course/'+courseId.value+'?withCatalogue=true')]);papers.value=list;course.value=detail;}
 catch(error){if(error instanceof ApiError && error.status===400 && error.message==='无课程学习权限'){enrollmentHint.value='当前没有这门课程的有效学习权益。报名后可参加考试；已有学习记录可在我的学习中查看。';return;}throw error;}
});}
async function chooseCourse(){attempt.value=undefined;papers.value=[];await load();await restore();}
async function restore(){const active=sessionStorage.getItem('school-active-exam'),activeCourse=sessionStorage.getItem('school-active-exam-course');if(active && (!courseId.value || activeCourse===courseId.value)){await task.run(async()=>{await showAttempt(await get<Row>('/exam-attempts/'+active));});}}
async function start(id:string){await task.run(async()=>{const operation=await ops.begin('exam','开始考试','/exam-papers/'+id+'/attempts',undefined);if(operation.status==='SUCCEEDED'){const result=operation.result as Row;await showAttempt(await get<Row>('/exam-attempts/'+result.id));sessionStorage.setItem('school-active-exam',String(result.id));sessionStorage.setItem('school-active-exam-course',courseId.value);}else task.message.value='考试正在创建，请在操作记录中查看结果';});}
async function refresh(){if(attempt.value)await task.run(async()=>{await showAttempt(await get<Row>('/exam-attempts/'+attempt.value!.id));});}
async function submit(){await task.run(async()=>{if(!attempt.value)return;if(!await savedDraft.sync())throw new Error('草稿尚未同步或发生冲突，请先处理草稿后提交');const operation=await ops.begin('exam','提交考试','/exam-attempts/'+attempt.value.id+'/submit',{answers:responses.value,version:savedDraft.version.value});if(operation.status==='SUCCEEDED'){await showAttempt(await get<Row>('/exam-attempts/'+attempt.value.id));submitOpen.value=false;}else task.message.value='答卷正在提交，请在操作记录中查看结果';});}
watch(()=>route.query.courseId,async value=>{courseId.value=String(value||'');await chooseCourse();});
onMounted(async()=>{if(!courseId.value)courseId.value=sessionStorage.getItem('school-active-exam-course')||'';await moreCourses();if(courseId.value)await load();await restore();});
function options(question:Row):string[]{if(Array.isArray(question.options) && question.options.length)return question.options;try{const parsed=JSON.parse(question.options||'[]');if(Array.isArray(parsed)&&parsed.length)return parsed;}catch{}return Number(question.type)===4?['正确','错误']:[];}
function checked(question:Row):string[]{return (responses.value[question.question_id]||'').split(',').filter(Boolean);}
function selectMultiple(question:Row,values:unknown){responses.value[question.question_id]=(values as string[]).join(',');}
</script>
<template><section class="card exam-page"><div class="section-heading"><div><p class="eyebrow">检验所学，巩固每一步进步</p><h2>课程考试</h2></div><RouterLink to="/learning">返回我的学习 →</RouterLink></div><p class="muted">提交后答案不可修改。客观题自动评分，主观题由教师评分；未通过可重新参加。</p><div class="toolbar"><el-select v-model="courseId" filterable placeholder="选择已报名课程" aria-label="选择考试课程" :disabled="task.busy.value" style="width:360px" @change="chooseCourse"><el-option v-if="course && !lessons.some((l:Row)=>String(l.courseId)===courseId)" :label="course.name" :value="courseId"/><el-option v-for="item in lessons" :key="item.id" :label="lessonLabel(item)" :disabled="!activeLesson(item)" :value="String(item.courseId)"/><template #footer><el-button v-if="lessons.length<lessonTotal" text @click="moreCourses" :disabled="task.busy.value">加载更多课程</el-button></template></el-select><el-button @click="load" :disabled="!courseId || task.busy.value || !!enrollmentHint">查询试卷</el-button></div><Status :busy="task.busy.value" :error="task.error.value" :message="task.message.value"/>
<el-alert v-if="enrollmentHint" :title="enrollmentHint" type="info" show-icon :closable="false" class="enrollment-hint"/>
<div v-if="papers.length" class="exam-paper-grid"><article v-for="paper in papers" :key="paper.id" class="paper-tile"><div class="paper-icon">测</div><div><h3>{{sectionName(paper.section_id)}}</h3><p class="muted">第 {{paper.version}} 版 · 总分 {{paper.total_score}} · {{Math.ceil(Number(paper.total_score)*Number(paper.pass_percent)/100)}} 分及格</p></div><el-button type="primary" plain @click="start(paper.id)" :disabled="task.busy.value">开始 / 继续考试</el-button></article></div>
<el-empty v-else-if="!task.busy.value && !task.error.value && !enrollmentHint" :description="courseId?'这门课程暂未发布试卷':'请选择已报名课程查看考试'"/>
<article v-if="attempt" class="answer-sheet"><div class="section-heading"><div><h3>我的答卷</h3><small>考试记录 {{attempt.id}}</small></div><el-tag :type="attempt.status==='FINISHED'?(Number(attempt.passed)===1?'success':'danger'):'warning'">{{examStatus(attempt.status)}}</el-tag></div>
<div v-if="attempt.status==='FINISHED'" class="exam-result"><strong>{{attempt.score}} <small>分</small></strong><span>{{Number(attempt.passed)===1?'已通过，继续下一段学习吧':'未通过，可以再次参加考试'}}</span></div>
<el-alert v-if="attempt.status==='WAIT_GRADING'" title="答卷已提交，正在等待教师评分。稍后可点击「刷新评分状态」查看结果。" type="info" :closable="false"/>
<p v-if="attempt.status==='IN_PROGRESS'" class="muted">已作答 {{answered}} / {{attempt.questions.length}} 题 · {{savedDraft.state.value}}。</p>
<div v-if="attempt.status==='IN_PROGRESS'" class="toolbar"><el-button v-if="!savedDraft.conflict.value" @click="savedDraft.sync":disabled="!savedDraft.ready.value">同步草稿</el-button><el-button v-else type="warning" @click="loadLatestDraft">载入最新草稿</el-button><el-button v-if="Object.keys(savedDraft.backup.value).length" @click="backupOpen=true">查看本机备份</el-button></div>
<div v-for="(question,i) in attempt.questions" :key="question.question_id" class="exam-question"><h4><span class="question-number">{{Number(i)+1}}</span>{{question.name}} <small>{{typeName(question.type)}} · {{question.score}} 分</small></h4>
<el-checkbox-group v-if="[2,3].includes(Number(question.type)) && options(question).length" :model-value="checked(question)" class="answer-options" :disabled="attempt.status!=='IN_PROGRESS' || !savedDraft.ready.value" @update:model-value="selectMultiple(question,$event)"><el-checkbox v-for="(option,j) in options(question)" :key="j" :value="String(j+1)">{{String.fromCharCode(65+Number(j))}}. {{option}}</el-checkbox></el-checkbox-group>
<el-radio-group v-else-if="Number(question.type)!==5 && options(question).length" v-model="responses[question.question_id]" class="answer-options" :disabled="attempt.status!=='IN_PROGRESS' || !savedDraft.ready.value"><el-radio v-for="(option,j) in options(question)" :key="j" :value="String(j+1)">{{String.fromCharCode(65+Number(j))}}. {{option}}</el-radio></el-radio-group>
<el-input v-else v-model="responses[question.question_id]" type="textarea" :rows="5" maxlength="10000" :disabled="attempt.status!=='IN_PROGRESS' || !savedDraft.ready.value" :placeholder="Number(question.type)===5?'请写下你的答案':'此题未配置选项，请填写答案编号；如有疑问联系教师'"/>
<p v-for="answer in (attempt.answers||[]).filter((a:Row)=>a.question_id===question.question_id)" :key="answer.question_id" class="answer-feedback">得分 {{answer.score??'待评分'}}<span v-if="answer.feedback"> · 教师反馈：{{answer.feedback}}</span></p></div>
<div class="toolbar"><el-button v-if="attempt.status==='IN_PROGRESS'" type="primary" size="large" @click="submitOpen=true" :disabled="task.busy.value || savedDraft.conflict.value || !savedDraft.ready.value">提交全部答案</el-button><el-button @click="refresh" :disabled="task.busy.value">刷新评分状态</el-button></div></article>
<el-dialog v-model="backupOpen" title="本机未同步答案备份"><p class="muted">这是载入最新草稿前保存的本机答案。可复制内容后在当前答卷重新填写；不会自动覆盖服务器草稿。</p><article v-for="question in attempt?.questions||[]" :key="question.question_id"><h4>{{question.name}}</h4><el-input :model-value="savedDraft.backup.value[question.question_id]||'未作答'" type="textarea" readonly :rows="3"/></article></el-dialog>
<el-dialog v-model="submitOpen" title="确认提交答卷" class="purchase-dialog"><Status :error="task.error.value" :busy="task.busy.value"/><p>已作答 {{answered}} / {{attempt?.questions.length||0}} 题。提交后不能修改答案。</p><el-alert v-if="answered<(attempt?.questions.length||0)" title="还有未作答题目，未作答的客观题将计为 0 分。" type="warning" :closable="false"/><template #footer><el-button @click="submitOpen=false">继续检查</el-button><el-button type="primary" @click="submit" :disabled="task.busy.value">确认提交答卷</el-button></template></el-dialog></section></template>
