<script setup lang="ts">
import {ref,onMounted,watch} from 'vue';import {useRoute} from 'vue-router';const route=useRoute();import {get} from '../../../../packages/shared/src/client';import {useOperations} from '../../../../packages/shared/src/operations';import {useTask,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const courseId=ref(''),papers=ref<Row[]>([]),attempt=ref<Row>(),responses=ref<Record<string,string>>({}),task=useTask(),ops=useOperations();
async function load(){await task.run(async()=>{papers.value=await get<Row[]>('/exam-papers?courseId='+encodeURIComponent(courseId.value));});}
async function start(id:string){await task.run(async()=>{const operation=await ops.begin('exam','开始考试','/exam-papers/'+id+'/attempts',undefined);if(operation.status==='SUCCEEDED'){const result=operation.result as Row;attempt.value=await get<Row>('/exam-attempts/'+result.id);sessionStorage.setItem('school-active-exam',String(result.id));responses.value=JSON.parse(sessionStorage.getItem('school-exam-draft-'+result.id)||'{}');}});}
async function refresh(){if(attempt.value)await task.run(async()=>{attempt.value=await get<Row>('/exam-attempts/'+attempt.value!.id);});}
async function submit(){await task.run(async()=>{if(!attempt.value)return;const operation=await ops.begin('exam','提交考试','/exam-attempts/'+attempt.value.id+'/submit',{answers:responses.value});if(operation.status==='SUCCEEDED')attempt.value=await get<Row>('/exam-attempts/'+attempt.value.id);});}
watch(responses,()=>{if(attempt.value?.status==='IN_PROGRESS')sessionStorage.setItem('school-exam-draft-'+attempt.value.id,JSON.stringify(responses.value));},{deep:true});
onMounted(async()=>{courseId.value=String(route.query.courseId||'');if(courseId.value)await load();const active=sessionStorage.getItem('school-active-exam');if(active)await task.run(async()=>{attempt.value=await get<Row>('/exam-attempts/'+active);responses.value=JSON.parse(sessionStorage.getItem('school-exam-draft-'+active)||'{}');});});
function options(question:Row):string[]{if(Array.isArray(question.options))return question.options;try{return JSON.parse(question.options||'[]');}catch{return [];}}
</script>
<template><section class="card"><h2>课程考试</h2><p class="muted">提交后答案不可修改。客观题自动评分；主观题等待教师评分。未通过可以重考。</p><div class="toolbar"><el-input v-model="courseId" placeholder="课程 ID"/><el-button @click="load">查询试卷</el-button></div><Status :busy="task.busy.value" :error="task.error.value"/>
<el-table :data="papers"><el-table-column prop="section_id" label="考试小节"/><el-table-column prop="version" label="试卷版本"/><el-table-column prop="total_score" label="总分"/><el-table-column prop="pass_percent" label="及格比例（%）"/><el-table-column label="操作"><template #default="{row}"><el-button @click="start(row.id)" :disabled="task.busy.value">开始 / 继续考试</el-button></template></el-table-column></el-table>
<article v-if="attempt" class="card"><h3>考试记录 {{attempt.id}}</h3><el-tag>{{attempt.status}}</el-tag><p v-if="attempt.status==='FINISHED'">得分 {{attempt.score}} · {{Number(attempt.passed)===1?'已通过':'未通过'}}</p>
<div v-for="(question,i) in attempt.questions" :key="question.question_id" class="section"><h4>{{Number(i)+1}}. {{question.name}}（{{question.score}} 分）</h4><ol v-if="options(question).length"><li v-for="(option,j) in options(question)" :key="j">{{j+1}}. {{option}}</li></ol><el-input v-model="responses[question.question_id]" type="textarea" :disabled="attempt.status!=='IN_PROGRESS'" :placeholder="Number(question.type)===2?'多个选项编号以逗号分隔':'填写答案或选项编号'"/><p v-for="answer in (attempt.answers||[]).filter((a:Row)=>a.question_id===question.question_id)" :key="answer.question_id">答案 {{answer.response}} · 得分 {{answer.score??'待评分'}} · {{answer.feedback}}</p></div>
<el-button v-if="attempt.status==='IN_PROGRESS'" type="primary" @click="submit" :disabled="task.busy.value">提交全部答案</el-button><el-button @click="refresh">刷新评分状态</el-button></article></section></template>