<script setup lang="ts">
import {ref,watch,onMounted} from 'vue';import {get,write} from '../../../../packages/shared/src/client';import {useOperations} from '../../../../packages/shared/src/operations';import {useTask,query,type Row} from '../../../../packages/shared/src/ui';import Status from '../../../../packages/shared/src/Status.vue';
const props=defineProps<{mode:string}>(),task=useTask(),ops=useOperations(),rows=ref<Row[]>([]),total=ref(0),page=ref(1),courseId=ref(''),editing=ref<Row>(),content=ref(''),profile=ref<Row>({}),oldPassword=ref(''),password=ref(''),freq=ref(3),board=ref<Row>(),signs=ref<unknown>();
const titles:Record<string,string>={learning:'我的学习',favorites:'收藏课程',notes:'私人笔记',points:'积分与签到',messages:'消息中心',settings:'个人设置'};
async function load(){editing.value=undefined;await task.run(async()=>{
 if(props.mode==='settings'){profile.value=await get<Row>('/services/user/users/me');return;}
 if(props.mode==='points'){rows.value=await get<Row[]>('/services/learning/points/today');board.value=await get<Row>('/services/learning/boards?pageNo='+page.value+'&pageSize=20');signs.value=await get('/sign-ins');return;}
 const path=props.mode==='learning'?'/services/learning/lessons/page':props.mode==='favorites'?'/favorites':props.mode==='notes'?'/notes':'/services/message/inboxes';
 const result=await get<Row>(path+'?'+query({pageNo:page.value,pageSize:20,courseId:courseId.value}));rows.value=result.list||[];total.value=Number(result.total||0);
});}
async function updateNote(){const saved=await task.run(async()=>{if(!editing.value)return false;const result=await ops.begin('learning','编辑私人笔记','/notes/'+editing.value.id,{content:content.value,version:editing.value.version},'PUT');if(result.status==='SUCCEEDED'){editing.value=undefined;return true;}return false;});if(saved){await load();task.message.value='笔记已更新';}}
async function deleteNote(row:Row){const result=await task.run(()=>ops.begin('learning','删除私人笔记','/notes/'+row.id+'?version='+row.version,undefined,'DELETE'));if(result?.status==='SUCCEEDED')await load();}
watch(()=>props.mode,()=>{page.value=1;rows.value=[];void load();});onMounted(load);
</script>
<template><section class="card"><h2>{{titles[mode]}}</h2><Status :busy="task.busy.value"  :error="editing?undefined:task.error.value" :message="task.message.value"/>
<div v-if="mode==='notes'" class="toolbar"><el-input v-model="courseId" placeholder="按课程 ID 筛选"/><el-button @click="page=1;load()">查询</el-button><p>笔记默认私有。并发编辑冲突时请刷新后重新编辑。</p></div>
<div v-if="mode==='learning'" class="grid"><article v-for="row in rows" :key="row.id" class="card"><h3><RouterLink :to="'/courses/'+row.courseId">{{row.courseName}}</RouterLink></h3><el-progress :percentage="row.sections?Math.min(100,Math.round(row.learnedSections/row.sections*100)):0"/><p>学习状态 {{row.status}} · 有效期 {{row.expireTime||'永久'}}</p><el-input-number v-model="freq" :min="1" :max="7"/><el-button @click="task.run(async()=>{await write('/services/learning/lessons/plans','POST',{courseId:row.courseId,freq});task.message.value='学习计划已保存';})">每周学习计划</el-button></article></div>
<el-table v-else-if="mode==='favorites'" :data="rows"><el-table-column prop="course_id" label="课程 ID"/><el-table-column label="操作"><template #default="{row}"><RouterLink :to="'/courses/'+row.course_id">查看课程</RouterLink><el-button @click="task.run(async()=>{await write('/favorites/'+row.course_id,'DELETE');rows=rows.filter(x=>x.course_id!==row.course_id);})">取消收藏</el-button></template></el-table-column></el-table>
<template v-else-if="mode==='notes'"><article v-for="row in rows" :key="row.id" class="section"><RouterLink :to="'/courses/'+row.course_id">课程 {{row.course_id}}</RouterLink><small> 小节 {{row.section_id}} · {{row.moment??0}} 秒 · 版本 {{row.version}}</small><p class="content">{{row.content}}</p><el-button @click="editing=row;content=row.content">编辑</el-button><el-popconfirm title="删除这条私人笔记？" @confirm="deleteNote(row)"><template #reference><el-button>删除</el-button></template></el-popconfirm></article><el-dialog  :model-value="!!editing" title="编辑笔记" @update:model-value="(value:boolean)=>{if(!value)editing=undefined;}" :before-close="()=>{editing=undefined;}"><Status :error="task.error.value" :busy="task.busy.value"/><el-input v-model="content" type="textarea" :rows="8" maxlength="10000"/><template #footer><el-button type="primary" @click="updateNote" :disabled="!content.trim() || task.busy.value">保存</el-button></template></el-dialog></template>
<template v-else-if="mode==='points'"><div class="toolbar"><el-button type="primary" @click="task.run(async()=>{const r=await ops.begin('learning','每日签到','/sign-ins',undefined);task.message.value=r.status==='SUCCEEDED'?'签到成功':'签到处理中';})" :disabled="task.busy.value">今日签到</el-button><el-button @click="load">刷新积分</el-button></div><p>我的排名 {{board?.rank||'暂无'}} · 积分 {{board?.points||0}}</p><el-table :data="rows"><el-table-column prop="type" label="积分来源"/><el-table-column prop="points" label="今日积分"/><el-table-column prop="maxPoints" label="每日上限"/></el-table><h3>积分排行榜</h3><el-table :data="board?.boardList||[]"><el-table-column prop="rank" label="排名"/><el-table-column prop="name" label="用户"/><el-table-column prop="points" label="积分"/></el-table></template>
<template v-else-if="mode==='messages'"><article v-for="row in rows" :key="row.id" class="section"><h3>{{row.title||row.subject}}</h3><p class="content">{{row.content}}</p><small>{{row.pushTime}}</small><el-button v-if="!row.isRead" @click="task.run(async()=>{await write('/services/message/inboxes/'+row.id+'/read','PUT');row.isRead=true;})">标为已读</el-button><span v-else>已读</span></article></template>
<el-form v-else-if="mode==='settings'" label-width="90px"><el-form-item label="昵称"><el-input v-model="profile.name" maxlength="50"/></el-form-item><el-form-item label="简介"><el-input v-model="profile.intro" type="textarea"/></el-form-item><el-form-item label="原密码"><el-input v-model="oldPassword" type="password" autocomplete="current-password"/></el-form-item><el-form-item label="新密码（可选）"><el-input v-model="password" type="password" autocomplete="new-password"/></el-form-item><el-button type="primary" @click="task.run(async()=>{await write('/services/user/users','PUT',{...profile,oldPassword,password});task.message.value='个人信息已保存';})" :disabled="task.busy.value || (!!password && !oldPassword)">保存</el-button></el-form>
<el-empty v-if="!rows.length && !task.busy.value && !task.error.value && !['settings','points'].includes(mode)" description="暂无记录"/><el-pagination v-if="!['settings','points'].includes(mode)" v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next" @current-change="load"/></section></template>
