<script setup lang="ts">
import {ref,computed,onMounted,watch} from 'vue';import {get,request,type ApiError} from '../../../../packages/shared/src/client';import {type Row} from '../../../../packages/shared/src/ui';
const props=defineProps<{modelValue:Row;busy:boolean}>(),emit=defineEmits<{save:[body:Row];cancel:[]}>();
const model=ref<Row>({...props.modelValue}),price=ref(Number(props.modelValue.price||0)/100),categories=ref<Row[]>([]),simulated=ref(false),uploading=ref(false),error=ref(''),imageFailed=ref(false);
const ended=computed(()=>!!model.value.purchaseEndTime && new Date(model.value.purchaseEndTime).getTime()<Date.now());
const ready=computed(()=>!!model.value.name?.trim() && !!model.value.thirdCateId && !!model.value.coverUrl?.trim() && (model.value.free || price.value>0) && !!model.value.purchaseEndTime && !!model.value.introduce?.trim() && !!model.value.usePeople?.trim() && !!model.value.detail?.trim() && !uploading.value && !props.busy);
watch(()=>model.value.coverUrl,()=>imageFailed.value=false);
onMounted(async()=>{try{categories.value=await get<Row[]>('/services/course/categorys/list?status=1');simulated.value=(await get<Row>('/environment')).mode==='SIMULATED';}catch(e){error.value=e instanceof Error?e.message:'配置加载失败';}});
async function upload(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;error.value='';if(!['image/png','image/jpeg'].includes(file.type)||file.size>5*1024*1024){error.value='请选择不超过 5 MiB 的 PNG 或 JPEG 图片';input.value='';return;}uploading.value=true;try{const body=new FormData();body.set('file',file);const result=await request<{path:string}>('/admin/course-cover-upload',{method:'POST',body});model.value.coverUrl=result.path;}catch(e){error.value=e instanceof Error?e.message:'封面上传失败';}finally{uploading.value=false;input.value='';}}
function save(){error.value='';if(!ready.value)return;if(!model.value.id && ended.value){error.value='新课程的报名截止时间必须晚于当前时间';return;}if(model.value.purchaseStartTime && new Date(model.value.purchaseStartTime)>new Date(model.value.purchaseEndTime)){error.value='报名开始时间不能晚于截止时间';return;}if(!/^(https?:\/\/|\/)/.test(model.value.coverUrl)){error.value='封面地址应为 HTTP 图片地址或站内路径';return;}emit('save',{...model.value,price:model.value.free?0:Math.round(price.value*100)});}
</script>
<template><el-form label-position="top" class="course-base-form"><el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <el-alert v-if="ended" title="该课程报名已结束。可以保存内容修正，截止时间保持原值；重新上架前需要确认新的报名计划。" type="warning" :closable="false"/>
 <div class="grid"><el-form-item label="课程名称" required><el-input v-model="model.name" aria-label="课程名称" maxlength="100"/></el-form-item>
 <el-form-item label="课程分类" required><el-cascader v-model="model.thirdCateId" :options="categories" :props="{value:'id',label:'name',children:'children',emitPath:false}" filterable aria-label="选择课程分类" placeholder="选择三级分类"/></el-form-item></div>
 <el-form-item label="课程封面" required><div class="cover-editor"><img v-if="model.coverUrl && !imageFailed" :src="model.coverUrl" alt="课程封面预览" @error="imageFailed=true"/><p v-else class="muted">{{imageFailed?'原封面无法显示，请重新上传或填写可访问地址':'尚未设置封面'}}</p><input v-if="simulated" aria-label="上传课程封面" type="file" accept="image/png,image/jpeg" :disabled="uploading||busy" @change="upload"/></div><el-input v-model="model.coverUrl" aria-label="封面地址" placeholder="也可填写现有的图片地址"/><small class="muted">{{uploading?'正在保存封面…':'本地封面使用持久地址；PNG / JPEG，最大 5 MiB。'}}</small><small v-if="!simulated" class="muted">当前环境请填写已配置存储的图片地址。</small></el-form-item>
 <div class="grid"><el-form-item label="免费课程"><el-switch v-model="model.free" aria-label="免费课程"/></el-form-item><el-form-item v-if="!model.free" label="课程价格（元）" required><el-input-number v-model="price" aria-label="课程价格（元）" :min="0.01" :precision="2" :step="1"/></el-form-item>
 <el-form-item label="报名截止" required><el-date-picker v-model="model.purchaseEndTime" aria-label="报名截止" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item>
 <el-form-item label="学习有效期（月，0 表示永久）"><el-input-number v-model="model.validDuration" :min="0"/></el-form-item></div>
 <el-form-item label="课程介绍" required><el-input v-model="model.introduce" aria-label="课程介绍" type="textarea" :rows="3" placeholder="简要介绍课程内容"/></el-form-item><el-form-item label="适用人群" required><el-input v-model="model.usePeople" aria-label="适用人群"/></el-form-item><el-form-item label="课程详情" required><el-input v-model="model.detail" aria-label="课程详情" type="textarea" :rows="7" placeholder="完整课程说明；支持保存原有 HTML 内容"/></el-form-item>
 <div class="toolbar"><el-button @click="emit('cancel')">取消</el-button><el-button type="primary" @click="save" :disabled="!ready">保存课程资料</el-button></div></el-form></template>
